const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-7'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=['hook','pcTable','pcGraph','imperfectTable','imperfectGraph','trCompare','significance','graphDetective','assertion','board','boss','finish'];
const labels={'hook':'Revenue curves: mixed practice','pcTable':'Perfect competition table','pcGraph':'Perfect competition graphs','imperfectTable':'Imperfect competition table','imperfectGraph':'Imperfect competition graphs','trCompare':'TR under different markets','significance':'Significance of revenue curves','graphDetective':'Graph Application','assertion':'Assertion–Reason','board':'Board answer','boss':'Comprehensive practice','finish':'Chapter complete'};
const help={'hook':'The market structure affects the shapes and relationships of TR, AR and MR.','pcTable':'Under perfect competition an individual firm is a price taker, so price stays constant.','pcGraph':'AR and MR are horizontal because price is constant; TR is a straight rising line from the origin.','imperfectTable':'When a firm must lower price to sell more, AR falls and MR falls faster than AR.','imperfectGraph':'AR slopes downward and MR lies below AR because each extra sale usually requires a lower price.','trCompare':'Under perfect competition TR is a straight line from the origin; under imperfect competition it rises at a diminishing rate.','significance':'Revenue curves help the firm see how output affects total earnings, per-unit earnings and extra earnings.','graphDetective':'A horizontal AR/MR line belongs to perfect competition; downward AR with lower MR belongs to imperfect competition.','assertion':'Remember: under imperfect competition MR falls faster than AR.','board':'Link the market condition directly to the curve shape.','boss':'Use every part of the chapter: cost, revenue, averages, marginals and market-based curve behaviour.','finish':'You have now covered the full Cost and Revenue chapter.'};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look carefully at the economic relationship being tested.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};
$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`
<div class='eyebrow'>Cost & Revenue • Mission 7</div><h1>Revenue Curves</h1>
<div class='scene'><div class='sceneTitle'>Now connect revenue back to forms of market.</div><p>Under perfect competition, one more unit sells at the same price. Under imperfect competition, firms usually have to lower price to sell more, so MR falls faster than AR.</p></div>`;if(t==='pcTable')m.innerHTML=`
<div class='eyebrow'>Perfect competition</div><h2>TR, AR and MR under perfect competition</h2>
<div class='tableWrap panel'><table class='table'><tr><th>Q</th><th>Price</th><th>TR</th><th>AR</th><th>MR</th></tr><tr><td>1</td><td>₹40</td><td>₹40</td><td>₹40</td><td>₹40</td></tr><tr><td>2</td><td>₹40</td><td>₹80</td><td>₹40</td><td>₹40</td></tr><tr><td>3</td><td>₹40</td><td>₹120</td><td>₹40</td><td>₹40</td></tr></table></div>
<div class='equation'>Perfect competition: P = AR = MR</div>`;if(t==='pcGraph')m.innerHTML=`
<div class='eyebrow'>Graph intuition</div><h2>What do the revenue curves look like under perfect competition?</h2>
<div class='plotGrid'><div class='chartwrap panel'><svg viewBox='0 0 430 270'><line x1='50' y1='20' x2='50' y2='220' class='chartAxis'/><line x1='50' y1='220' x2='390' y2='220' class='chartAxis'/><line x1='50' y1='110' x2='390' y2='110' class='chartCurve'/><text x='8' y='28' class='chartLabel'>Revenue</text><text x='290' y='248' class='chartLabel'>Output</text><text x='275' y='100' class='chartLabel'>AR = MR = P</text></svg></div><div class='chartwrap panel'><svg viewBox='0 0 430 270'><line x1='50' y1='20' x2='50' y2='220' class='chartAxis'/><line x1='50' y1='220' x2='390' y2='220' class='chartAxis'/><line x1='50' y1='220' x2='360' y2='40' class='chartCurve'/><text x='8' y='28' class='chartLabel'>TR</text><text x='290' y='248' class='chartLabel'>Output</text><text x='310' y='60' class='chartLabel'>TR</text></svg></div></div>
<div class='callout'>One graph shows per-unit revenue staying constant; the other shows total revenue rising proportionately with output.</div>`;if(t==='imperfectTable')m.innerHTML=`
<div class='eyebrow'>Imperfect competition</div><h2>TR, AR and MR under imperfect competition</h2>
<div class='tableWrap panel'><table class='table'><tr><th>Q</th><th>Price / AR</th><th>TR</th><th>MR</th></tr><tr><td>1</td><td>₹100</td><td>₹100</td><td>₹100</td></tr><tr><td>2</td><td>₹90</td><td>₹180</td><td>₹80</td></tr><tr><td>3</td><td>₹80</td><td>₹240</td><td>₹60</td></tr></table></div>
<div class='callout'>To sell one more unit, the firm lowers price. Therefore, <b>MR &lt; AR</b>.</div>
<div class='questionCard'><b>In this table, which statement is true?</b><div class='answers'><button class='ans q' data-v='mrless'>MR is less than AR after the first unit.</button><button class='ans q' data-v='mrequal'>MR always equals AR.</button><button class='ans q' data-v='trfall'>TR falls from 1 to 3 units.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='imperfectGraph')m.innerHTML=`
<div class='eyebrow'>Graph intuition</div><h2>AR and MR under imperfect competition</h2>
<div class='chartwrap panel'><svg viewBox='0 0 460 300'><line x1='60' y1='20' x2='60' y2='250' class='chartAxis'/><line x1='60' y1='250' x2='420' y2='250' class='chartAxis'/><line x1='90' y1='70' x2='385' y2='205' class='chartCurve'/><line x1='90' y1='50' x2='370' y2='230' class='budgetLine'/><text x='15' y='30' class='chartLabel'>Revenue</text><text x='315' y='280' class='chartLabel'>Output</text><text x='350' y='195' class='chartLabel'>AR</text><text x='338' y='233' class='chartLabel'>MR</text></svg></div>
<div class='callout'>MR lies below AR because the firm sacrifices some price on existing units when it cuts price to sell extra units.</div>`;if(t==='trCompare')m.innerHTML=`
<div class='eyebrow'>Total revenue comparison</div><h2>How does TR behave?</h2>
<div class='compare'><div class='panel'><h3>Perfect competition</h3><p>TR rises in direct proportion to output.</p><div class='equation' style='font-size:26px'>straight line from origin</div></div><div class='op'>VS</div><div class='panel'><h3>Imperfect competition</h3><p>TR rises at a diminishing rate because price falls as output rises.</p><div class='equation' style='font-size:26px'>bending curve</div></div></div>`;if(t==='significance')m.innerHTML=`
<div class='eyebrow'>Why the curves matter</div><h2>Significance of revenue curves</h2>
<div class='grid3'><div class='panel'><h3>TR curve</h3><p>Shows total earning behaviour as output changes.</p></div><div class='panel'><h3>AR curve</h3><p>Shows revenue per unit and often doubles as the demand curve for the firm.</p></div><div class='panel'><h3>MR curve</h3><p>Shows how much each extra unit adds to revenue.</p></div></div>`;if(t==='graphDetective')m.innerHTML=`
<div class='eyebrow'>Exam pattern</div><h2>Which market form is hidden in the graph?</h2>
<div class='paperCard'><p>A firm’s AR and MR curves coincide in a horizontal line parallel to the X-axis. Which market form does this indicate?</p></div>
<div class='questionCard'><b>Choose the best answer.</b><div class='answers'><button class='ans q' data-v='perfect'>Perfect competition</button><button class='ans q' data-v='monopoly'>Monopoly</button><button class='ans q' data-v='monoComp'>Monopolistic competition</button></div><div id='fb' class='feedback'></div></div>`;if(t==='assertion')m.innerHTML=`
<div class='eyebrow'>Assertion–Reason</div><h2>Assertion–Reason</h2>
<div class='paperCard'><p><b>Assertion:</b> Under imperfect competition, MR is less than AR.</p><p><b>Reason:</b> In order to sell more units, the firm usually lowers price.</p></div>
<div class='questionCard'><b>Pick the best option.</b><div class='answers'><button class='ans q' data-v='both'>Both are true and the reason explains the assertion.</button><button class='ans q' data-v='false'>Assertion false, reason true.</button><button class='ans q' data-v='bothno'>Both are true but the reason does not explain the assertion.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='board')m.innerHTML=`
<div class='eyebrow'>Board Answer Coach</div><h2>“Explain why AR = MR under perfect competition.”</h2>
<div class='board'><p>Under perfect competition, the firm is a price taker and sells each unit at the same market price. Therefore, average revenue, which is revenue per unit, is equal to price. Since each additional unit also adds the same price to total revenue, marginal revenue is also equal to price. Hence, AR = MR = Price.</p></div>
<div class='questionCard'><b>What gives the answer its logic?</b><div class='answers'><button class='ans q' data-v='priceTaker'>It begins with the price-taker condition and derives the equality from it.</button><button class='ans q' data-v='formula'>It only uses formulas.</button><button class='ans q' data-v='words'>It uses many words.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='boss')m.innerHTML=`
<div class='eyebrow'>Comprehensive Practice</div><h2>Comprehensive Practice: The popcorn stall</h2>
<div class='caseFile'><b>CASE</b><p>A popcorn stall sells each packet at ₹50 under a price-taking market. At 10 packets, total cost is ₹420 and total revenue is ₹500. At 11 packets, total cost is ₹470 and total revenue is ₹550.</p></div>
<div class='questionCard'><b>Which option is fully correct?</b><div class='answers'><button class='ans q' data-v='full'>At 10 packets, AC = ₹42; MR of the 11th packet = ₹50; MC of the 11th packet = ₹50; and under perfect competition AR = MR = Price.</button><button class='ans q' data-v='wrong1'>AC at 10 packets is ₹420 and MR of the 11th packet is ₹550.</button><button class='ans q' data-v='wrong2'>Under perfect competition MR must be less than AR.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='finish')m.innerHTML=`
<div class='eyebrow'>Mission complete</div><h1>Revenue Curves: Complete</h1>
<div class='coverageStrip'><p>✓ Cost concepts &nbsp; ✓ short-run costs &nbsp; ✓ AFC, AVC, AC, MC &nbsp; ✓ long-run costs &nbsp; ✓ TR, AR, MR &nbsp; ✓ revenue curves under different markets</p></div>
<p class='big'>One final question remains: at what output is the producer's profit highest?</p><a class='btn primary' href='mission.html?mission=cost-8'>Start Producer's Equilibrium →</a>`;
if(t==='imperfectTable')quiz('mrless','Correct. Because price must be lowered to sell more units, marginal revenue is less than average revenue.','Look carefully at the economic relationship being tested.');if(t==='graphDetective')quiz('perfect','Correct. A price-taking firm under perfect competition faces a horizontal AR = MR line.','Look carefully at the economic relationship being tested.');if(t==='assertion')quiz('both','Exactly. Lowering price to sell more is why MR lies below AR.','Look carefully at the economic relationship being tested.');if(t==='board')quiz('priceTaker','Yes. The price-taker condition is the real reason the relationship holds.','Look carefully at the economic relationship being tested.');if(t==='boss')quiz('full','Correct. AC = 420/10 = 42, MR = 550−500 = 50, MC = 470−420 = 50, and in perfect competition AR = MR = Price.','Look carefully at the economic relationship being tested.');
save();header()}
render();
