const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-1'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook","choice","opportunity","opportunityPractice","visibleHidden","explicit","implicit","economic","ledgerGame","real","realTrap","private","external","social","socialCase","compare","assertion","iscTransfer","board","boss","finish"];
const labels={hook:"What did it really cost?",choice:"Saturday choice",opportunity:"Opportunity cost",opportunityPractice:"Choose the sacrifice",visibleHidden:"Visible vs hidden costs",explicit:"Money / explicit cost",implicit:"Implicit cost",economic:"Economic cost",ledgerGame:"Build the ledger",real:"Real cost",realTrap:"Don't confuse real cost",private:"Private cost",external:"Costs pushed onto others",social:"Social cost",socialCase:"Who pays?",compare:"Master comparison",assertion:"Assertion–Reason",iscTransfer:"ISC transfer set",board:"Board answer coach",boss:"Cost detective boss",finish:"Mission complete"};
const help={hook:"Cost is not always the amount printed on a receipt. Economists also care about what you give up and who bears the sacrifice.",choice:"A choice uses scarce money or time. When you choose one option, another available option is sacrificed.",opportunity:"Opportunity cost is the value of the next-best alternative you give up. Not every alternative—just the best one you did not choose.",opportunityPractice:"Ask: if this choice disappeared, what would I most likely have chosen instead? That forgone option is the opportunity cost.",visibleHidden:"Some costs involve an actual payment. Others come from using something you already own or giving up income you could have earned.",explicit:"Explicit costs are actual monetary payments made by the producer, such as wages, rent paid, electricity bills and raw materials.",implicit:"Implicit costs do not require a cash payment. They are the value of self-owned resources used in the business instead of their next-best use.",economic:"Economic cost counts both explicit and implicit costs. It asks what resources truly cost the decision-maker, not just what the accountant sees leaving the bank account.",ledgerGame:"Put actual payments under explicit cost. Put forgone income from owned resources under implicit cost. Add them for economic cost.",real:"Real cost refers to the effort, sacrifice, discomfort or disutility involved in producing a good or service. It is not a price adjusted for inflation.",realTrap:"In this chapter, 'real cost' is the human sacrifice involved in production. Do not read it as 'real price' or 'inflation-adjusted money'.",private:"Private cost is borne directly by the producer or consumer making the decision.",external:"Sometimes part of the cost falls on someone outside the transaction. Pollution, noise and congestion are common examples.",social:"Social cost is the total cost to society. A useful way to think of it is private cost plus external cost.",socialCase:"Identify who pays the bill directly, then ask whether anyone else suffers a cost without being compensated.",compare:"Use the question each term answers: cash paid? forgone alternative? all resource cost? human sacrifice? cost to decision-maker? cost to society?",assertion:"Treat assertion and reason separately first. Decide whether each is true, then decide whether the reason actually explains the assertion.",iscTransfer:"The story is unfamiliar on purpose. Translate it into the cost question underneath.",board:"A strong answer defines the term, identifies the sacrificed alternative or cost bearer, then applies it to the case.",boss:"No labels now. Identify the cost concept from clues and explain why.",finish:"Next mission moves from meanings of cost to short-run fixed, variable and total cost."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look for what is actually being sacrificed or who actually bears the cost.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function money(n){return '₹'+Number(n).toLocaleString('en-IN')}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Cost & Revenue • Mission 1</div><h1>What did it <em>really</em> cost?</h1><div class="photoHero crHero"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Cafe_interior_-_San_Francisco%2C_CA.jpg/1280px-Cafe_interior_-_San_Francisco%2C_CA.jpg" alt="Interior of a cafe"><div class="photoOverlay"><b>Imagine this café is yours.</b><span>Rent, wages and coffee beans are obvious costs. But are they the whole story?</span></div></div><div class="callout"><b>Big idea:</b> economics counts more than receipts. It asks what resources were sacrificed and who ultimately bears the cost.</div><p class="sourceNote">Photo: Daderot / Wikimedia Commons, CC0.</p>`;
else if(t==='choice')m.innerHTML=`<div class="eyebrow">Start with a choice</div><h2>You have Saturday afternoon and ₹1,000.</h2><div class="choiceFork"><div class="forkCard imageFork"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Tennis_courts.jpg/1280px-Tennis_courts.jpg" alt="Tennis courts"><h3>Tennis lesson</h3><p>Costs ₹1,000 and uses your afternoon.</p></div><div class="forkOr">OR</div><div class="forkCard imageFork"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Stepmania-arcade.jpg/960px-Stepmania-arcade.jpg" alt="Arcade game machine"><h3>Arcade + movie</h3><p>Also uses the same afternoon and roughly the same budget.</p></div></div><p class="sourceNote">Photos: Kurt Kaiser and Hanno Böck / Wikimedia Commons, CC0.</p><div class="questionCard"><b>You choose the tennis lesson. Besides the ₹1,000, what else have you given up?</b><div class="answers"><button class="ans q" data-v="alt">The arcade + movie option you would otherwise have chosen</button><button class="ans q" data-v="everything">Every possible thing you could ever do on Saturday</button><button class="ans q" data-v="nothing">Nothing—only money counts as cost</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='opportunity')m.innerHTML=`<div class="eyebrow">Opportunity cost</div><h2>The cost hiding behind every choice.</h2><div class="sacrificeDiagram"><div class="chosenBox">✅ CHOSEN<br><b>Tennis lesson</b></div><div class="sacrificeArrow">means giving up →</div><div class="forgoneBox">❌ NEXT-BEST ALTERNATIVE<br><b>Arcade + movie</b></div></div><div class="definition"><div class="term">ISC-ready definition</div><p><b>Opportunity cost</b> is the value of the next-best alternative foregone when a choice is made.</p></div><div class="notice"><b>Two traps:</b> it is not every alternative you give up, and it is not automatically the money price of the option you chose.</div>`;
else if(t==='opportunityPractice')m.innerHTML=`<div class="eyebrow">Practice • Learn → Transfer</div><h2>What is the opportunity cost?</h2><div class="caseFile"><b>CASE</b><p>A student can spend Sunday preparing for an economics test, work a ₹1,500 shift, or attend a concert. She values the work shift more than the concert but chooses to study.</p></div><div class="answers"><button class="ans q" data-v="shift">The ₹1,500 work shift</button><button class="ans q" data-v="concert">The concert</button><button class="ans q" data-v="both">The shift + the concert together</button><button class="ans q" data-v="study">The time spent studying</button></div><div id="fb" class="feedback"></div>`;
else if(t==='visibleHidden')m.innerHTML=`<div class="eyebrow">Run a café</div><h2>Some costs show up on the bank statement. Others don't.</h2><div class="photoSplit"><div><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Cafe_interior_-_San_Francisco%2C_CA.jpg/1280px-Cafe_interior_-_San_Francisco%2C_CA.jpg" alt="Cafe interior"></div><div class="costLens"><div><b>💸 Visible payments</b><span>Wages, electricity, ingredients, rent paid to a landlord</span></div><div><b>👻 Hidden sacrifice</b><span>You use a shop you own and work there yourself instead of earning elsewhere</span></div></div></div><div class="callout">Economics wants <b>both</b> sides of that picture.</div>`;
else if(t==='explicit')m.innerHTML=`<div class="eyebrow">Money / Accounting / Explicit Cost</div><h2>Money actually paid out.</h2><div class="receipt"><div><span>Rent paid</span><b>₹30,000</b></div><div><span>Electricity</span><b>₹15,000</b></div><div><span>Employee wages</span><b>₹40,000</b></div><div class="receiptTotal"><span>Explicit cost</span><b>₹85,000</b></div></div><div class="definition"><div class="term">ISC-ready meaning</div><p><b>Money or explicit cost</b> consists of actual monetary payments made by a producer for hired factors and inputs used in production.</p></div><div class="notice">Your textbook may also use <b>accounting cost</b> in this visible-payment sense. We will keep the terminology side-by-side so the exam wording doesn't surprise you.</div>`;
else if(t==='implicit')m.innerHTML=`<div class="eyebrow">The cost with no bill</div><h2>You can sacrifice income without paying anyone.</h2><div class="hiddenCostGrid"><div><div class="emojiHero">🏪</div><b>Your own shop</b><p>You use it for the café instead of renting it out for ₹25,000.</p><strong>Implicit cost: ₹25,000</strong></div><div><div class="emojiHero">👤</div><b>Your own time</b><p>You run the café instead of taking a job paying ₹50,000.</p><strong>Implicit cost: ₹50,000</strong></div></div><div class="definition"><div class="term">Implicit cost</div><p>The estimated value of self-owned resources used in production, measured by the income they could have earned in their next-best use.</p></div>`;
else if(t==='economic')m.innerHTML=`<div class="eyebrow">Economic Cost</div><h2>Now count what the business really uses.</h2><div class="economicEquation"><div><small>EXPLICIT</small><strong>₹85,000</strong><span>cash payments</span></div><b>+</b><div><small>IMPLICIT</small><strong>₹75,000</strong><span>forgone income</span></div><b>=</b><div class="economicTotal"><small>ECONOMIC COST</small><strong>₹1,60,000</strong><span>full resource cost</span></div></div><div class="definition"><div class="term">ISC-ready relationship</div><p><b>Economic Cost = Explicit Cost + Implicit Cost.</b></p></div><div class="notice">This is why a business can show an accounting profit and still earn little or no <em>economic</em> profit later in the syllabus.</div>`;
else if(t==='ledgerGame')m.innerHTML=`<div class="eyebrow">Build the ledger</div><h2>Which side does each cost belong on?</h2><div class="caseFile"><p>A gaming café pays ₹20,000 rent, ₹8,000 electricity and ₹25,000 wages. The owner also works there instead of taking a ₹35,000 job.</p></div><div class="questionCard"><b>What is its economic cost?</b><div class="answers"><button class="ans q" data-v="88">₹88,000</button><button class="ans q" data-v="53">₹53,000</button><button class="ans q" data-v="35">₹35,000</button><button class="ans q" data-v="108">₹1,08,000</button></div><div id="fb" class="feedback"></div></div><div class="miniLedger"><span>Explicit: 20,000 + 8,000 + 25,000 = ₹53,000</span><span>Implicit: ₹35,000</span><span>Economic: ₹88,000</span></div>`;
else if(t==='real')m.innerHTML=`<div class="eyebrow">Real Cost</div><h2>Not every sacrifice can be read from an invoice.</h2><div class="humanCostScene"><div class="workerArt">🌙<br>🧑‍🏭</div><div><h3>12-hour night shift</h3><p>The employer may pay wages, but production can also involve fatigue, loss of leisure, discomfort and effort.</p><div class="humanCostFlow"><span>Sleep / leisure given up</span><span>Physical or mental effort</span><span>Discomfort / sacrifice</span></div></div></div><div class="definition"><div class="term">ISC-ready meaning</div><p><b>Real cost</b> refers to the pain, sacrifice, effort and disutility involved in producing a commodity or service.</p></div>`;
else if(t==='realTrap')m.innerHTML=`<div class="eyebrow">Misconception repair</div><h2>“Real cost” does NOT mean “price after inflation.”</h2><div class="compare"><div class="panel goodbg"><h3>✅ Here</h3><p>Real cost = human effort, sacrifice or disutility involved in production.</p></div><div class="op">≠</div><div class="panel warnbg"><h3>🚫 Not this concept</h3><p>“Real” as in inflation-adjusted purchasing power belongs to a different context.</p></div></div><div class="questionCard"><b>A surgeon gives up sleep and leisure during a long emergency shift. Which concept best captures that sacrifice?</b><div class="answers"><button class="ans q" data-v="real">Real cost</button><button class="ans q" data-v="explicit">Explicit cost</button><button class="ans q" data-v="private">Private cost only</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='private')m.innerHTML=`<div class="eyebrow">Private Cost</div><h2>Start with the people making the decision.</h2><div class="privateDiagram"><div class="decisionMaker">🏭 Factory</div><div class="arrowDown">↓ pays</div><div class="privateBills"><span>raw materials</span><span>wages</span><span>electricity</span><span>equipment</span></div></div><div class="definition"><div class="term">ISC-ready meaning</div><p><b>Private cost</b> is the cost borne by an individual producer or consumer as a result of an economic activity.</p></div>`;
else if(t==='external')m.innerHTML=`<div class="eyebrow">But what if somebody else pays?</div><h2>The factory's accounts may not contain the whole cost.</h2><div class="photoHero pollution"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Swedish_Factory_Pollution.jpg/1280px-Swedish_Factory_Pollution.jpg" alt="Factory releasing air pollution"><div class="photoOverlay"><b>The factory pays its own production bills.</b><span>Nearby residents may bear dirty air, health effects or cleaning costs without receiving compensation.</span></div></div><div class="costSpill"><div>🏭 <b>Private cost</b><span>borne by the producer</span></div><div class="spillArrow">cost spills outward →</div><div>🏘️ <b>External cost</b><span>borne by third parties</span></div></div><p class="sourceNote">Photo: “Swedish Factory Pollution” / Wikimedia Commons, CC0.</p>`;
else if(t==='social')m.innerHTML=`<div class="eyebrow">Social Cost</div><h2>Zoom out from the business to society.</h2><div class="socialEquation"><div><b>PRIVATE COST</b><span>what the decision-maker bears</span></div><strong>+</strong><div><b>EXTERNAL COST</b><span>cost imposed on others</span></div><strong>=</strong><div class="socialTotal"><b>SOCIAL COST</b><span>total cost to society</span></div></div><div class="definition"><div class="term">ISC-ready relationship</div><p><b>Social cost</b> is the total cost of an economic activity to society, including both private costs and external costs.</p></div><div class="notice">In simple form: <b>Social Cost = Private Cost + External Cost.</b></div>`;
else if(t==='socialCase')m.innerHTML=`<div class="eyebrow">Who actually pays?</div><h2>Noise after midnight.</h2><div class="caseFile"><b>CASE</b><p>A nightclub pays rent, wages and electricity. Its loud music also prevents nearby residents from sleeping, but the club does not compensate them.</p></div><div class="answers"><button class="ans q" data-v="external">The lost sleep suffered by residents is an external cost.</button><button class="ans q" data-v="explicit">The residents' lost sleep is an explicit cost of the nightclub.</button><button class="ans q" data-v="implicit">The residents' lost sleep is an implicit cost of the nightclub owner.</button><button class="ans q" data-v="none">There is no economic cost because no money changed hands.</button></div><div id="fb" class="feedback"></div>`;
else if(t==='compare')m.innerHTML=`<div class="eyebrow">Put the whole map together</div><h2>Six cost ideas. Six different questions.</h2><div class="tableWrap"><table class="table crTable"><thead><tr><th>Concept</th><th>Ask yourself</th><th>Example</th></tr></thead><tbody><tr><td>Explicit / money</td><td>Did money actually get paid?</td><td>Wages paid to staff</td></tr><tr><td>Implicit</td><td>Did I use my own resource and give up income?</td><td>Owner works without drawing market salary</td></tr><tr><td>Opportunity</td><td>What next-best alternative was sacrificed?</td><td>Job forgone to run café</td></tr><tr><td>Economic</td><td>What is the full resource cost?</td><td>Explicit + implicit</td></tr><tr><td>Real</td><td>What effort / pain / sacrifice occurs?</td><td>Fatigue from night work</td></tr><tr><td>Private / Social</td><td>Who bears the cost?</td><td>Factory bills vs pollution borne by community</td></tr></tbody></table></div>`;
else if(t==='assertion')m.innerHTML=`<div class="eyebrow">ISC Mode • Assertion–Reason</div><h2>Read each statement separately first.</h2><div class="paperCard"><p><b>Assertion:</b> Economic cost may exceed accounting cost.</p><p><b>Reason:</b> Economic cost includes the opportunity cost of self-owned resources used by the producer.</p></div><div class="answers"><button class="ans q" data-v="bothExplain">Both are true and the Reason correctly explains the Assertion.</button><button class="ans q" data-v="bothNo">Both are true but the Reason does not explain the Assertion.</button><button class="ans q" data-v="afalse">Assertion is false but Reason is true.</button><button class="ans q" data-v="rfalse">Assertion is true but Reason is false.</button></div><div id="fb" class="feedback"></div>`;
else if(t==='iscTransfer')m.innerHTML=`<div class="eyebrow">ISC Mode • Situation</div><h2>Identify the hidden concept.</h2><div class="paperCard"><p>Rhea owns a shop that could be rented for ₹18,000 per month. Instead, she uses it for her own bakery. She pays ₹45,000 in wages and ₹12,000 for electricity.</p><p><b>(i)</b> Identify the implicit cost. <b>(ii)</b> Calculate the economic cost from the information given.</p></div><div class="answers"><button class="ans q" data-v="75">Implicit cost ₹18,000; economic cost ₹75,000</button><button class="ans q" data-v="57">Implicit cost ₹0; economic cost ₹57,000</button><button class="ans q" data-v="63">Implicit cost ₹18,000; economic cost ₹63,000</button></div><div id="fb" class="feedback"></div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board Answer Coach</div><h2>“Differentiate between private cost and social cost with an example.”</h2><div class="board"><p><b>Private cost</b> is the cost borne directly by the producer or consumer undertaking an economic activity.</p><p><b>Social cost</b> is the total cost imposed on society and includes private cost as well as external cost borne by third parties.</p><p><b>Example:</b> A factory's wages, fuel and raw-material expenses are private costs. If its pollution harms nearby residents, that uncompensated harm is an external cost and forms part of the social cost.</p></div><div class="questionCard"><b>What makes this answer stronger than “private = personal, social = society”?</b><div class="answers"><button class="ans q" data-v="mechanism">It defines who bears each cost and applies the distinction to one coherent example.</button><button class="ans q" data-v="length">It is longer.</button><button class="ans q" data-v="jargon">It uses more difficult words.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='boss')m.innerHTML=`<div class="eyebrow">Final Boss</div><h2>No labels. Diagnose the cost.</h2><div class="caseFile"><b>CASE</b><p>Arjun leaves a ₹60,000-a-month job to run a café in a building he owns. He pays ₹35,000 wages and ₹10,000 utilities. The café's late-night delivery bikes also create noise for neighbours.</p></div><div class="bossGrid"><div><b>₹45,000</b><span>actual cash payments</span></div><div><b>₹60,000</b><span>salary forgone</span></div><div><b>🏘️ Noise</b><span>cost borne by neighbours</span></div></div><div class="questionCard"><b>Which statement is fully correct?</b><div class="answers"><button class="ans q" data-v="full">Explicit cost is ₹45,000; the forgone salary is an implicit/opportunity cost; the noise is an external cost.</button><button class="ans q" data-v="wrong1">Economic cost is only ₹45,000 because only actual payments count.</button><button class="ans q" data-v="wrong2">The neighbours' noise is a private cost because it came from the café.</button><button class="ans q" data-v="wrong3">The ₹60,000 salary is an explicit cost because it has a rupee value.</button></div><div id="fb" class="feedback"></div></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>You can now see costs that receipts miss.</h1><div class="coverageStrip"><p>✓ Money / accounting / explicit cost &nbsp; ✓ Opportunity cost &nbsp; ✓ Implicit cost &nbsp; ✓ Economic cost &nbsp; ✓ Real cost &nbsp; ✓ Private cost &nbsp; ✓ External + social cost</p></div><p class="big">Next: the food truck that costs money even when it sells nothing—fixed, variable and total cost.</p><a class="btn primary" href="cost.html">Back to Cost & Revenue map →</a>`;
if(t==='choice')quiz('alt','Exactly. The sacrificed next-best option is the hidden cost of the choice.','Not quite. Opportunity cost focuses on the single next-best alternative you actually give up.');
if(t==='opportunityPractice')quiz('shift','Correct. Since the work shift is the best alternative she would otherwise choose, its value is the opportunity cost.');
if(t==='ledgerGame')quiz('88','Correct. ₹53,000 explicit + ₹35,000 implicit = ₹88,000 economic cost.','Add the actual payments first, then include the owner’s forgone salary.');
if(t==='realTrap')quiz('real','Correct. The focus is human effort and sacrifice, so this is real cost.');
if(t==='socialCase')quiz('external','Correct. The residents bear a cost even though they are outside the nightclub transaction.');
if(t==='assertion')quiz('bothExplain','Correct. Accounting cost excludes implicit costs, while economic cost includes them, so economic cost can be larger.');
if(t==='iscTransfer')quiz('75','Correct. ₹18,000 rent forgone is implicit cost. Economic cost = 18,000 + 45,000 + 12,000 = ₹75,000.','Remember to include the rent Rhea could have earned from her own shop.');
if(t==='board')quiz('mechanism','Exactly. A board answer earns strength from a clear distinction plus application, not length for its own sake.');
if(t==='boss')quiz('full','Boss cleared. You separated actual payment, forgone income and third-party harm correctly.','Track each item by the question it answers: money paid, income forgone, or cost imposed on outsiders.');
save();header()}
render();
