const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-8'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook","meaning","profit","trtcIdea","trtcTable","trtcGraph","trtcCondition","mrmcBridge","mrmcTable","mrmcCondition1","mrmcCondition2","mrmcGraph","falseEquilibrium","compareApproaches","jargon","iscCase","assertion","board","boss","finish"];
const labels={hook:"The producer's question",meaning:"Meaning of producer's equilibrium",profit:"Profit-maximisation goal",trtcIdea:"TR–TC approach",trtcTable:"Find maximum profit",trtcGraph:"TR–TC graph",trtcCondition:"TR–TC conditions",mrmcBridge:"From totals to the next unit",mrmcTable:"MR–MC table",mrmcCondition1:"Condition 1: MR = MC",mrmcCondition2:"Condition 2: MC must rise",mrmcGraph:"MR–MC graph",falseEquilibrium:"Why equality alone is not enough",compareApproaches:"Two approaches, same answer",jargon:"Jargon & mark magnets",iscCase:"ISC transfer case",assertion:"Assertion–Reason",board:"Board answer coach",boss:"Producer equilibrium boss",finish:"Mission complete"};
const help={hook:"Producer's equilibrium asks which output gives the producer the greatest possible profit. It is not the same as market equilibrium between demand and supply.",meaning:"The producer is in equilibrium when there is no incentive to increase or decrease output because profit is maximised at that output.",profit:"Profit is total revenue minus total cost. So the equilibrium output is where that difference is greatest, not merely where revenue is highest.",trtcIdea:"Under the TR–TC approach, calculate profit at each output and choose the output where TR − TC is maximum.",trtcTable:"Subtract TC from TR row by row. The largest positive difference is maximum profit.",trtcGraph:"On a graph, profit is the vertical gap between TR and TC. Equilibrium occurs where this gap is greatest.",trtcCondition:"The TR–TC method asks for maximum positive difference between total revenue and total cost. At the maximum-gap point, the slopes of TR and TC are equal.",mrmcBridge:"MR asks what one more unit adds to revenue. MC asks what one more unit adds to cost. Compare them to decide whether producing another unit helps profit.",mrmcTable:"If MR exceeds MC, the extra unit adds more revenue than cost, so profit rises. If MC exceeds MR, the extra unit reduces profit.",mrmcCondition1:"MR = MC is necessary because at equilibrium the extra unit adds exactly as much revenue as cost.",mrmcCondition2:"Equality alone is not sufficient. MC must cut MR from below (or MC must be rising at the intersection) so that profit changes from rising to falling.",mrmcGraph:"Read the graph from left to right: before equilibrium MR > MC; at equilibrium MR = MC; after equilibrium MC > MR.",falseEquilibrium:"If MC crosses MR from above, profit is moving from falling to rising. That is not a maximum-profit equilibrium.",compareApproaches:"TR–TC and MR–MC are two ways of locating the same profit-maximising output: one uses totals; the other uses changes from one extra unit.",jargon:"These are the terms examiners expect: profit maximisation, equilibrium output, MR = MC, MC cuts MR from below, maximum difference between TR and TC.",iscCase:"Ignore the business story and identify the profit logic: compare MR and MC or compare TR and TC.",assertion:"Judge the assertion and reason separately, then check whether the reason truly explains the assertion.",board:"A complete answer states both MR–MC conditions and explains why each matters. Writing only MR = MC is incomplete.",boss:"Use both approaches. Check the maximum TR−TC difference, then confirm the MR–MC conditions.",finish:"Producer's equilibrium completes the Cost & Revenue unit and prepares you for firm equilibrium under perfect competition."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Track what happens to profit before and after the proposed equilibrium output.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Cost & Revenue • Mission 8</div><h1>How much should the producer make?</h1><div class="scene"><div class="sceneTitle">A bakery can sell more cakes. But should it?</div><p>More sales increase revenue. More production also increases cost. The producer's real question is not “How much can I sell?” It is:</p><div class="equation" style="color:white">At what output is PROFIT highest?</div></div><div class="conceptStrip"><div><b>TR − TC</b><span>Look for the biggest profit gap.</span></div><div><b>MR vs MC</b><span>Ask whether the next unit helps profit.</span></div><div><b>Equilibrium</b><span>No reason to change output.</span></div></div>`;
else if(t==='meaning')m.innerHTML=`<div class="eyebrow">Definition layer</div><h2>Producer's equilibrium</h2><div class="heroDefinition"><div class="giantTerm">PE</div><div><div class="definition"><div class="term">ISC-ready meaning</div><p><b>Producer's equilibrium</b> is the level of output at which the producer earns maximum profit and has no tendency to increase or decrease output.</p></div><div class="callout"><b>Plain English:</b> the producer has found the output that makes profit as large as possible.</div></div></div><div class="notice"><b>Do not confuse it with market equilibrium.</b> Market equilibrium is where market demand equals market supply. Producer's equilibrium is about one producer's profit-maximising output.</div>`;
else if(t==='profit')m.innerHTML=`<div class="eyebrow">The goal</div><h2>Highest revenue is NOT the same as highest profit.</h2><div class="economicEquation"><div><small>Total Revenue</small><strong>₹1,000</strong><span>money earned</span></div><b>−</b><div><small>Total Cost</small><strong>₹700</strong><span>money/resources used</span></div><b>=</b><div class="economicTotal"><small>Profit</small><strong>₹300</strong><span>TR − TC</span></div></div><div class="questionCard"><b>A producer's TR rises from ₹1,000 to ₹1,200, but TC rises from ₹700 to ₹1,050. Did profit rise?</b><div class="answers"><button class="ans q" data-v="no">No. Profit falls from ₹300 to ₹150.</button><button class="ans q" data-v="yes">Yes. Revenue increased.</button><button class="ans q" data-v="same">Profit stays the same.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='trtcIdea')m.innerHTML=`<div class="eyebrow">Approach 1</div><h2>TR–TC approach: find the biggest gap</h2><div class="miniFlow centered"><span>Choose output</span><b>→</b><span>Find TR</span><b>→</b><span>Find TC</span><b>→</b><span>Profit = TR − TC</span><b>→</b><span>Choose maximum profit</span></div><div class="definition"><div class="term">TR–TC condition</div><p>The producer is in equilibrium at the output where the <b>positive difference between TR and TC is maximum</b>.</p></div>`;
else if(t==='trtcTable')m.innerHTML=`<div class="eyebrow">Calculation</div><h2>Which output maximises profit?</h2><div class="tableWrap panel"><table class="table"><thead><tr><th>Output</th><th>TR (₹)</th><th>TC (₹)</th><th>Profit = TR−TC</th></tr></thead><tbody><tr><td>1</td><td>100</td><td>130</td><td>−30</td></tr><tr><td>2</td><td>200</td><td>190</td><td>10</td></tr><tr><td>3</td><td>300</td><td>240</td><td>60</td></tr><tr><td>4</td><td>400</td><td>310</td><td><b>90</b></td></tr><tr><td>5</td><td>500</td><td>430</td><td>70</td></tr></tbody></table></div><div class="questionCard"><b>Producer's equilibrium output is:</b><div class="answers"><button class="ans q" data-v="4">4 units</button><button class="ans q" data-v="5">5 units, because TR is highest</button><button class="ans q" data-v="3">3 units</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='trtcGraph')m.innerHTML=`<div class="eyebrow">Graph lab</div><h2>TR–TC equilibrium on a graph</h2><div class="chartwrap panel"><svg viewBox="0 0 560 350" role="img" aria-label="TR and TC curves with maximum vertical profit gap"><line x1="60" y1="25" x2="60" y2="295" class="chartAxis"/><line x1="60" y1="295" x2="515" y2="295" class="chartAxis"/><line x1="60" y1="295" x2="475" y2="70" class="chartCurve"/><path d="M60 235 C150 225,220 190,300 145 S420 80,490 48" class="budgetLine"/><line x1="324" y1="132" x2="324" y2="158" stroke="#ef4444" stroke-width="5"/><line x1="312" y1="132" x2="336" y2="132" stroke="#ef4444" stroke-width="3"/><line x1="312" y1="158" x2="336" y2="158" stroke="#ef4444" stroke-width="3"/><text x="12" y="30" class="chartLabel">Cost / Revenue</text><text x="414" y="325" class="chartLabel">Output</text><text x="447" y="82" class="chartLabel">TR</text><text x="454" y="48" class="chartLabel">TC</text><text x="340" y="150" class="chartLabel">maximum profit gap</text></svg></div><div class="graphSteps"><div><b>1</b><span>Vertical distance between TR and TC = profit.</span></div><div><b>2</b><span>Find where that positive distance is greatest.</span></div><div><b>3</b><span>That output is producer's equilibrium.</span></div></div>`;
else if(t==='trtcCondition')m.innerHTML=`<div class="eyebrow">Theory layer</div><h2>What exactly are the TR–TC conditions?</h2><div class="grid2"><div class="panel"><h3>Primary condition</h3><p>The positive difference between <b>TR and TC must be maximum</b>.</p></div><div class="panel"><h3>Graph consequence</h3><p>At the maximum-gap point, the <b>slopes of TR and TC are equal</b>. Since slope of TR = MR and slope of TC = MC, this leads us to MR = MC.</p></div></div><div class="callout">This is why the two equilibrium approaches are not unrelated tricks. They describe the same profit maximum in two different languages.</div>`;
else if(t==='mrmcBridge')m.innerHTML=`<div class="eyebrow">Approach 2</div><h2>Forget totals for a moment. Should I make the NEXT unit?</h2><div class="grid3"><div class="panel goodbg"><h3>MR &gt; MC</h3><p>The next unit adds more revenue than cost.</p><b>Produce more → profit rises.</b></div><div class="panel soft"><h3>MR = MC</h3><p>The next unit adds exactly as much revenue as cost.</p><b>Possible equilibrium.</b></div><div class="panel warnbg"><h3>MR &lt; MC</h3><p>The next unit adds more cost than revenue.</p><b>Producing more reduces profit.</b></div></div>`;
else if(t==='mrmcTable')m.innerHTML=`<div class="eyebrow">Read the next unit</div><h2>MR–MC table</h2><div class="tableWrap panel"><table class="table"><thead><tr><th>Output</th><th>MR (₹)</th><th>MC (₹)</th><th>What happens to profit?</th></tr></thead><tbody><tr><td>1</td><td>100</td><td>40</td><td>Rises</td></tr><tr><td>2</td><td>100</td><td>55</td><td>Rises</td></tr><tr><td>3</td><td>100</td><td>75</td><td>Rises</td></tr><tr><td>4</td><td><b>100</b></td><td><b>100</b></td><td>Maximum reached</td></tr><tr><td>5</td><td>100</td><td>135</td><td>Falls</td></tr></tbody></table></div><div class="questionCard"><b>Why should the firm NOT go from 4 to 5 units?</b><div class="answers"><button class="ans q" data-v="cost">Because unit 5 adds ₹135 cost but only ₹100 revenue.</button><button class="ans q" data-v="equal">Because MR and MC are equal at unit 5.</button><button class="ans q" data-v="tr">Because total revenue becomes zero.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='mrmcCondition1')m.innerHTML=`<div class="eyebrow">First condition</div><h2>Condition 1: MR = MC</h2><div class="heroDefinition"><div class="giantTerm">MR = MC</div><div><p>If MR &gt; MC, producing another unit adds to profit. If MR &lt; MC, producing that unit reduces profit. So equilibrium requires the point at which the two are equal.</p></div></div><div class="notice"><b>But stop:</b> MR = MC by itself is not enough. This is a classic exam trap.</div>`;
else if(t==='mrmcCondition2')m.innerHTML=`<div class="eyebrow">Second condition</div><h2>Condition 2: MC must cut MR from below</h2><div class="causeChain"><div><b>Before equilibrium</b><span>MR &gt; MC → profit is rising</span></div><div class="chainArrow">→</div><div><b>At equilibrium</b><span>MR = MC</span></div><div class="chainArrow">→</div><div><b>After equilibrium</b><span>MC &gt; MR → profit falls</span></div></div><div class="definition"><div class="term">Board-ready condition</div><p>MC must be rising and should cut MR from below at the equilibrium output.</p></div>`;
else if(t==='mrmcGraph')m.innerHTML=`<div class="eyebrow">Graph lab</div><h2>Producer's equilibrium using MR and MC</h2><div class="chartwrap panel"><svg viewBox="0 0 560 350" role="img" aria-label="Horizontal MR curve and U shaped MC curve intersecting on rising MC"><line x1="60" y1="25" x2="60" y2="295" class="chartAxis"/><line x1="60" y1="295" x2="515" y2="295" class="chartAxis"/><line x1="60" y1="150" x2="510" y2="150" class="chartCurve"/><path d="M85 105 C150 185,225 235,300 205 S390 125,475 55" class="budgetLine"/><circle cx="370" cy="150" r="7" class="chartDot"/><line x1="370" y1="150" x2="370" y2="295" stroke="#98a2b3" stroke-width="2" stroke-dasharray="7 6"/><text x="15" y="30" class="chartLabel">Cost / Revenue</text><text x="415" y="325" class="chartLabel">Output</text><text x="470" y="140" class="chartLabel">MR</text><text x="465" y="60" class="chartLabel">MC</text><text x="350" y="322" class="chartLabel">Qe</text><text x="380" y="135" class="chartLabel">E</text></svg></div><div class="graphSteps"><div><b>Before E</b><span>MR is above MC, so more output adds to profit.</span></div><div><b>At E</b><span>MR = MC.</span></div><div><b>After E</b><span>MC is above MR, so more output reduces profit.</span></div></div>`;
else if(t==='falseEquilibrium')m.innerHTML=`<div class="eyebrow">Harder theory</div><h2>Two intersections? Only one may maximise profit.</h2><div class="chartwrap panel"><svg viewBox="0 0 560 330"><line x1="60" y1="25" x2="60" y2="275" class="chartAxis"/><line x1="60" y1="275" x2="515" y2="275" class="chartAxis"/><line x1="60" y1="145" x2="510" y2="145" class="chartCurve"/><path d="M90 75 C165 180,230 220,300 190 S405 105,485 50" class="budgetLine"/><circle cx="140" cy="145" r="7" class="chartDot"/><circle cx="365" cy="145" r="7" class="chartDot"/><text x="120" y="130" class="chartLabel">A</text><text x="375" y="130" class="chartLabel">B</text><text x="465" y="135" class="chartLabel">MR</text><text x="455" y="55" class="chartLabel">MC</text></svg></div><div class="questionCard"><b>Which intersection is the profit-maximising equilibrium?</b><div class="answers"><button class="ans q" data-v="B">B, because MC cuts MR from below there.</button><button class="ans q" data-v="A">A, because any MR = MC point is equilibrium.</button><button class="ans q" data-v="both">Both A and B.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='compareApproaches')m.innerHTML=`<div class="eyebrow">Summary table</div><h2>TR–TC vs MR–MC</h2><div class="tableWrap panel"><table class="table crTable"><thead><tr><th>Approach</th><th>What you compare</th><th>Equilibrium condition</th><th>What it means</th></tr></thead><tbody><tr><td><b>TR–TC</b></td><td>Total revenue and total cost</td><td>TR − TC is maximum</td><td>Total profit is greatest</td></tr><tr><td><b>MR–MC</b></td><td>Extra revenue and extra cost</td><td>MR = MC and MC cuts MR from below</td><td>Profit stops rising and begins to fall</td></tr></tbody></table></div><div class="callout"><b>Same destination, different route.</b> One looks at the whole profit gap. The other looks at whether the next unit still improves profit.</div>`;
else if(t==='jargon')m.innerHTML=`<div class="eyebrow">Exam language</div><h2>Jargon Decoder: words that make the answer score</h2><div class="tableWrap panel"><table class="table crTable"><thead><tr><th>Jargon</th><th>What it means</th><th>Write this for marks</th></tr></thead><tbody><tr><td><b>Profit maximisation</b></td><td>Making profit as large as possible</td><td>maximum positive difference between TR and TC</td></tr><tr><td><b>Equilibrium output</b></td><td>The output the firm has no reason to change</td><td>no tendency to increase or decrease output</td></tr><tr><td><b>MR = MC</b></td><td>Next unit adds equal revenue and cost</td><td>necessary condition of producer's equilibrium</td></tr><tr><td><b>MC cuts MR from below</b></td><td>Before E profit rises; after E profit falls</td><td>MC must be rising at the equilibrium point</td></tr><tr><td><b>Maximum profit gap</b></td><td>TR is furthest above TC</td><td>positive difference between TR and TC is maximum</td></tr></tbody></table></div><div class="markBox"><b>🎯 Mark magnets</b><div class="keywordRow"><span class="keyword">profit maximisation</span><span class="keyword">TR − TC maximum</span><span class="keyword">MR = MC</span><span class="keyword">MC cuts MR from below</span><span class="keyword">equilibrium output</span></div></div>`;
else if(t==='iscCase')m.innerHTML=`<div class="eyebrow">ISC-style transfer</div><h2>Don't just find equality. Diagnose the direction of profit.</h2><div class="paperCard"><p>A producer has the following marginal values at three consecutive output levels:</p><p>At 6 units: MR = ₹90, MC = ₹70<br>At 7 units: MR = ₹90, MC = ₹90<br>At 8 units: MR = ₹90, MC = ₹115</p><p>Identify the equilibrium output and justify your answer.</p></div><div class="questionCard"><b>Best answer:</b><div class="answers"><button class="ans q" data-v="7">7 units. MR = MC there, with MR &gt; MC before it and MC &gt; MR after it.</button><button class="ans q" data-v="6">6 units because MR is greater than MC.</button><button class="ans q" data-v="8">8 units because MC is highest.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='assertion')m.innerHTML=`<div class="eyebrow">Assertion–Reason</div><h2>Exam trap</h2><div class="paperCard"><p><b>Assertion:</b> Every point at which MR = MC is a producer's equilibrium.</p><p><b>Reason:</b> For profit maximisation, MC must cut MR from below at the equilibrium output.</p></div><div class="questionCard"><b>Choose the correct option.</b><div class="answers"><button class="ans q" data-v="AFRT">Assertion is false; Reason is true.</button><button class="ans q" data-v="both">Both are true and Reason explains Assertion.</button><button class="ans q" data-v="ATRF">Assertion is true; Reason is false.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board Answer Coach</div><h2>“State and explain the conditions of producer's equilibrium using the MR–MC approach.”</h2><div class="board"><p><b>First condition:</b> Marginal revenue must be equal to marginal cost, i.e. <b>MR = MC</b>.</p><p><b>Second condition:</b> Marginal cost must be rising and must <b>cut marginal revenue from below</b> at the equilibrium output.</p><p>When MR &gt; MC, an additional unit adds more to revenue than to cost, so increasing output raises profit. When MC &gt; MR, an additional unit adds more to cost than revenue, so increasing output lowers profit. Hence profit is maximised where MR = MC subject to the second condition.</p></div><div class="questionCard"><b>Which omission would make this answer incomplete?</b><div class="answers"><button class="ans q" data-v="second">Leaving out “MC cuts MR from below / MC is rising”.</button><button class="ans q" data-v="business">Not naming a real business example.</button><button class="ans q" data-v="colour">Not drawing the graph in colour.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='boss')m.innerHTML=`<div class="eyebrow">Final Boss</div><h2>Prove the producer is in equilibrium two ways.</h2><div class="caseFile"><b>CASE</b><p>A firm has maximum TR−TC difference at 6 units. At 5 units MR is ₹80 and MC is ₹60; at 6 units MR = MC = ₹80; at 7 units MR is ₹80 and MC is ₹105.</p></div><div class="questionCard"><b>Which explanation is complete?</b><div class="answers"><button class="ans q" data-v="full">6 units is equilibrium because TR−TC is maximum, and under MR–MC, MR = MC at 6 while MR &gt; MC before and MC &gt; MR after.</button><button class="ans q" data-v="equal">6 units only because MR = MC.</button><button class="ans q" data-v="revenue">7 units because revenue from another unit is still positive.</button></div><div id="fb" class="feedback"></div></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>Now Cost & Revenue is actually complete.</h1><div class="coverageStrip"><p>✓ Producer's equilibrium meaning &nbsp; ✓ Profit maximisation &nbsp; ✓ TR–TC approach &nbsp; ✓ MR–MC approach &nbsp; ✓ both conditions &nbsp; ✓ diagrams &nbsp; ✓ ISC reasoning</p></div><p class="big">Next connection: equilibrium of a perfectly competitive firm, including break-even and shut-down points, belongs under Forms of Market.</p><div class="actions"><a class="btn primary" href="cost.html">Cost & Revenue map →</a><a class="btn secondary" href="review.html?unit=cost">Revision Hub</a></div>`;
if(t==='profit')quiz('no','Correct. Profit changes from ₹300 to ₹150. Revenue alone does not determine equilibrium.');
if(t==='trtcTable')quiz('4','Correct. Profit is maximum at 4 units: ₹400 − ₹310 = ₹90.');
if(t==='mrmcTable')quiz('cost','Correct. The fifth unit costs ₹135 to produce but adds only ₹100 to revenue, so it reduces profit.');
if(t==='falseEquilibrium')quiz('B','Correct. At B, MC crosses MR from below: before B, MR > MC; after B, MC > MR.','MR = MC is necessary, but you must also check the direction in which MC crosses MR.');
if(t==='iscCase')quiz('7','Exactly. The equality occurs at 7 units and the surrounding values confirm that profit changes from rising to falling.');
if(t==='assertion')quiz('AFRT','Correct. Equality can occur at a non-maximising intersection, so the assertion is false. The second condition is true.');
if(t==='board')quiz('second','Exactly. Writing only MR = MC misses the second condition and can cost marks.');
if(t==='boss')quiz('full','Boss cleared. You verified the same profit-maximising output using both total and marginal approaches.');
save();header()}
render();
