const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-2'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=['hook','shortRun','foodTruck','fixed','variable','tfcCurve','tvcCurve','tcCurve','tableBuild','compare','graphMatch','iscCase','board','boss','finish'];
const labels={'hook':'Even when you sell nothing','shortRun':'What does short run mean?','fixed':'Fixed cost intuition','variable':'Variable cost intuition','tfcCurve':'Why TFC is horizontal','tvcCurve':'Why TVC rises','tcCurve':'TC = TFC + TVC','tableBuild':'Build the cost table','compare':'Fixed vs variable','graphMatch':'Graph detective','board':'Board answer coach','boss':'Short-run cost boss','finish':'Mission complete','foodTruck':'See it: the food truck','iscCase':'ISC case: zero output'};
const help={'hook':'Short run means the firm cannot change everything at once. Some costs stay fixed for the period, while others change with output.','shortRun':'Short run does not mean a fixed number of days. It means at least one factor cannot be changed immediately.','fixed':'Ask: if output becomes zero, does this cost still remain? If yes, it is fixed in the short run.','variable':'Ask: if output rises, does this cost rise too? If yes, it is variable.','tfcCurve':'TFC is horizontal because the amount remains unchanged as output changes.','tvcCurve':'Variable cost starts from zero when output is zero, then rises as output rises.','tcCurve':'Total cost is simply the sum of fixed and variable cost at each output level.','tableBuild':'Use the formula row by row: TC = TFC + TVC.','compare':'Fixed cost is linked to the period, not output. Variable cost is linked to output.','graphMatch':'A horizontal cost curve is the one that remains constant with output.','board':'A good board answer defines the term and then directly applies it to a simple example.','boss':'Classify each item by asking whether it depends on output or simply on the passage of the period.','finish':'You now have the short-run base needed for average and marginal cost in the next mission.','foodTruck':'A photo makes the short-run idea concrete: the vehicle/permit exists before the next burger is made, while ingredients are added as output rises.','iscCase':'His papers often hide the concept inside a practical situation. Work from the story, then name the cost.'};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look carefully at the economic relationship being tested.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};
$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`
<div class='eyebrow'>Cost & Revenue • Mission 2</div><h1>Even when you sell nothing</h1>
<div class='scene'><div class='sceneTitle'>Imagine a food truck.</div><p>Some costs hit the owner even before the first burger is sold. Other costs rise only when output rises. That is the heart of <b>short-run cost</b>.</p></div>
<div class='conceptStrip'><div><b>Zero output</b><span>Some cost still exists.</span></div><div><b>More output</b><span>Some cost rises as production rises.</span></div><div><b>Big goal</b><span>Separate fixed, variable and total cost.</span></div></div>
<div class='callout'><b>Big idea:</b> in the short run, output can change faster than some inputs can.</div>`;if(t==='shortRun')m.innerHTML=`
<div class='eyebrow'>Start with the time idea</div><h2>What is the short run?</h2>
<div class='grid2'><div class='panel'><h3>Short run</h3><p>At least one factor remains fixed. The owner cannot instantly change everything about the business.</p><ul><li>Truck permit stays the same</li><li>Kitchen size stays the same</li><li>Loan payment stays the same</li></ul></div><div class='panel'><h3>Output can still change</h3><p>The truck can make and sell more or fewer burgers by changing ingredients, packaging, or hours of casual labour.</p></div></div>
<div class='definition'><div class='term'>ISC idea</div><p>In the short run, some factors are fixed and some are variable. Therefore, some costs do not change with output, while others do.</p></div>`;
if(t==='foodTruck')m.innerHTML=`
<div class='eyebrow'>See the business</div><h2>Freeze the food truck before the first sale.</h2>
<div class='photoHero lessonPhoto'><img src='https://commons.wikimedia.org/wiki/Special:Redirect/file/Austin_Texas_food_truck.jpg' alt='Food truck in Austin, Texas'><div class='photoOverlay'><b>Before customer #1 arrives...</b><span>The truck, licence, insurance and financing are already there. Buns, fillings and packaging are used as orders arrive.</span></div></div>
<div class='fourLens'><div><b>🚚 Truck / rent</b><span>Fixed for the period</span></div><div><b>📄 Permit</b><span>Fixed for the period</span></div><div><b>🥯 Ingredients</b><span>Change with output</span></div><div><b>📦 Packaging</b><span>Change with output</span></div></div>
<p class='sourceNote'>Photo: Wikimedia Commons, CC0.</p><div class='callout'><b>Don’t memorize the examples.</b> Ask whether the cost changes when output changes.</div>`;if(t==='fixed')m.innerHTML=`
<div class='eyebrow'>Who still gets paid?</div><h2>Costs that stay even at 0 burgers</h2>
<div class='grid3'><div class='panel'><h3>Permit / licence</h3><p>Still due even if the truck is closed today.</p></div><div class='panel'><h3>Insurance</h3><p>Still paid for the period.</p></div><div class='panel'><h3>Truck loan / rent</h3><p>Still has to be paid.</p></div></div>
<div class='definition'><div class='term'>Total Fixed Cost (TFC)</div><p>Fixed cost is the cost which remains constant irrespective of output in the short run.</p><div class='formal'><b>Shortcut:</b> output changes, this cost does not.</div></div>
<div class='questionCard'><b>If the food truck sells 0 burgers today, which of these still remains?</b><div class='answers'><button class='ans q' data-v='permit'>Daily permit / truck loan</button><button class='ans q' data-v='bun'>Burger buns</button><button class='ans q' data-v='sauce'>Sauce sachets used per burger</button></div><div id='fb' class='feedback'></div></div>`;if(t==='variable')m.innerHTML=`
<div class='eyebrow'>What changes when production changes?</div><h2>Costs that rise with output</h2>
<div class='grid3'><div class='panel'><h3>Buns</h3><p>More burgers → more buns.</p></div><div class='panel'><h3>Patties / vegetables</h3><p>More output means more ingredients.</p></div><div class='panel'><h3>Packaging</h3><p>Each extra unit needs wrapping or boxes.</p></div></div>
<div class='definition'><div class='term'>Total Variable Cost (TVC)</div><p>Variable cost is the cost which varies directly with output in the short run.</p><div class='formal'><b>Shortcut:</b> no output, almost no variable cost; more output, more variable cost.</div></div>
<div class='questionCard'><b>Which cost is most clearly variable?</b><div class='answers'><button class='ans q' data-v='ingredients'>Ingredients used for each burger</button><button class='ans q' data-v='insurance'>Annual insurance premium</button><button class='ans q' data-v='loan'>Truck loan</button></div><div id='fb' class='feedback'></div></div>`;if(t==='tfcCurve')m.innerHTML=`
<div class='eyebrow'>Graph intuition</div><h2>Why is the TFC curve horizontal?</h2>
<div class='plotGrid'><div class='tableWrap panel'><table class='table'><tr><th>Burgers</th><th>TFC (₹)</th></tr><tr><td>0</td><td>500</td></tr><tr><td>10</td><td>500</td></tr><tr><td>20</td><td>500</td></tr><tr><td>30</td><td>500</td></tr></table></div><div class='chartwrap panel'><svg viewBox='0 0 420 260'><line x1='60' y1='20' x2='60' y2='220' class='chartAxis'/><line x1='60' y1='220' x2='390' y2='220' class='chartAxis'/><line x1='60' y1='80' x2='390' y2='80' class='chartCurve'/><text x='8' y='28' class='chartLabel'>Cost</text><text x='300' y='250' class='chartLabel'>Output</text><text x='330' y='70' class='chartLabel'>TFC = ₹500</text><g class='chartGrid'><line x1='60' y1='120' x2='390' y2='120'/><line x1='60' y1='160' x2='390' y2='160'/><line x1='120' y1='20' x2='120' y2='220'/><line x1='200' y1='20' x2='200' y2='220'/><line x1='280' y1='20' x2='280' y2='220'/></g></svg></div></div>
<div class='callout'>Each row shows the same TFC. When the table stays flat, the graph becomes a horizontal line.</div><div class='graphExplain'><b>Read the graph</b><ul><li><b>Y-axis:</b> cost in rupees.</li><li><b>X-axis:</b> output produced.</li><li><b>What to notice:</b> moving right changes output, but the height of TFC never changes.</li></ul></div>`;if(t==='tvcCurve')m.innerHTML=`
<div class='eyebrow'>Graph intuition</div><h2>Why does TVC rise with output?</h2>
<div class='plotGrid'><div class='tableWrap panel'><table class='table'><tr><th>Burgers</th><th>TVC (₹)</th></tr><tr><td>0</td><td>0</td></tr><tr><td>10</td><td>300</td></tr><tr><td>20</td><td>520</td></tr><tr><td>30</td><td>780</td></tr></table></div><div class='chartwrap panel'><svg viewBox='0 0 420 260'><line x1='60' y1='20' x2='60' y2='220' class='chartAxis'/><line x1='60' y1='220' x2='390' y2='220' class='chartAxis'/><path d='M60 220 C120 170,180 150,220 120 S320 60,380 35' class='chartCurve'/><text x='8' y='28' class='chartLabel'>Cost</text><text x='300' y='250' class='chartLabel'>Output</text><text x='280' y='50' class='chartLabel'>TVC</text><g class='chartGrid'><line x1='60' y1='120' x2='390' y2='120'/><line x1='60' y1='160' x2='390' y2='160'/><line x1='120' y1='20' x2='120' y2='220'/><line x1='200' y1='20' x2='200' y2='220'/><line x1='280' y1='20' x2='280' y2='220'/></g></svg></div></div>
<div class='callout'>At zero output there are no ingredient or packaging costs. As output rises, TVC rises.</div><div class='graphExplain'><b>Read the graph</b><ul><li><b>Y-axis:</b> variable cost.</li><li><b>X-axis:</b> output.</li><li><b>Origin:</b> at zero output, TVC is zero.</li><li><b>Direction:</b> more production requires more variable inputs, so TVC rises.</li></ul></div>`;if(t==='tcCurve')m.innerHTML=`
<div class='eyebrow'>Bring them together</div><h2>Total cost is the full bill</h2>
<div class='equation'>TC = TFC + TVC</div>
<div class='plotGrid'><div class='tableWrap panel'><table class='table'><tr><th>Output</th><th>TFC</th><th>TVC</th><th>TC</th></tr><tr><td>0</td><td>500</td><td>0</td><td>500</td></tr><tr><td>10</td><td>500</td><td>300</td><td>800</td></tr><tr><td>20</td><td>500</td><td>520</td><td>1,020</td></tr><tr><td>30</td><td>500</td><td>780</td><td>1,280</td></tr></table></div><div class='panel'><h3>Notice the pattern</h3><ul><li>TC starts at the level of TFC.</li><li>TC always lies above TVC by the amount of TFC.</li><li>If TFC is ₹500, the vertical gap between TC and TVC is always ₹500.</li></ul></div></div>`;if(t==='tableBuild')m.innerHTML=`
<div class='eyebrow'>Table drill</div><h2>Fill the missing total cost</h2>
<div class='tableWrap panel'><table class='table'><tr><th>Output</th><th>TFC</th><th>TVC</th><th>TC</th></tr><tr><td>15</td><td>₹400</td><td>₹450</td><td>?</td></tr></table></div>
<div class='questionCard'><b>What is total cost?</b><div class='answers'><button class='ans q' data-v='850'>₹850</button><button class='ans q' data-v='450'>₹450</button><button class='ans q' data-v='400'>₹400</button></div><div id='fb' class='feedback'></div></div>`;if(t==='compare')m.innerHTML=`
<div class='eyebrow'>Sort the ideas</div><h2>Fixed cost vs variable cost</h2>
<div class='compare'><div class='panel'><h3>Fixed cost</h3><ul><li>Exists even at zero output</li><li>Does not change with output</li><li>Example: rent, insurance</li></ul></div><div class='op'>VS</div><div class='panel'><h3>Variable cost</h3><ul><li>Changes with output</li><li>Usually zero at zero output</li><li>Example: raw materials, packaging</li></ul></div></div>
<div class='questionCard'><b>A bakery pays monthly rent and also spends on flour. Which pair is correct?</b><div class='answers'><button class='ans q' data-v='rentflour'>Rent = fixed, flour = variable</button><button class='ans q' data-v='flourrent'>Flour = fixed, rent = variable</button><button class='ans q' data-v='bothfixed'>Both fixed</button></div><div id='fb' class='feedback'></div></div>`;if(t==='graphMatch')m.innerHTML=`
<div class='eyebrow'>Exam pattern</div><h2>Which curve must be horizontal?</h2>
<div class='paperCard'><p>A firm is in the short run. Which of the following cost curves is represented by a horizontal line parallel to the X-axis?</p><p>(A) TVC &nbsp;&nbsp; (B) TC &nbsp;&nbsp; (C) TFC &nbsp;&nbsp; (D) MC</p></div>
<div class='questionCard'><b>Choose the correct option.</b><div class='answers'><button class='ans q' data-v='C'>C. TFC</button><button class='ans q' data-v='A'>A. TVC</button><button class='ans q' data-v='B'>B. TC</button></div><div id='fb' class='feedback'></div></div>`;
if(t==='iscCase')m.innerHTML=`
<div class='eyebrow'>ISC Mode • application</div><h2>Read the situation, not the buzzwords.</h2>
<div class='paperCard'><p>A small bakery pays ₹24,000 monthly rent and ₹6,000 insurance. It spends ₹35 on ingredients for every loaf baked. Due to a power failure it produces no loaves for one day.</p><p><b>Which statement is correct?</b></p></div>
<div class='answers'><button class='ans q' data-v='correct'>Rent and insurance remain fixed costs; ingredient cost for that day's zero output is zero.</button><button class='ans q' data-v='allzero'>All costs become zero because output is zero.</button><button class='ans q' data-v='ingredientfixed'>Ingredients are fixed because bread normally requires them.</button></div><div id='fb' class='feedback'></div>`;if(t==='board')m.innerHTML=`
<div class='eyebrow'>Board Answer Coach</div><h2>“Distinguish between fixed cost and variable cost.”</h2>
<div class='board'><p><b>Fixed cost</b> is the cost which remains constant irrespective of output in the short run. For example, rent of a factory building.</p><p><b>Variable cost</b> is the cost which varies with the level of output in the short run. For example, expenditure on raw materials.</p></div>
<div class='questionCard'><b>Why is this answer better than only listing examples?</b><div class='answers'><button class='ans q' data-v='definition'>It first states the rule, then gives an example.</button><button class='ans q' data-v='length'>Because it is longer.</button><button class='ans q' data-v='hardwords'>Because it uses harder words.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='boss')m.innerHTML=`
<div class='eyebrow'>Final Boss</div><h2>Cost detective: the cupcake stall</h2>
<div class='caseFile'><b>CASE</b><p>A cupcake stall pays ₹2,000 monthly rent, ₹700 insurance, and spends ₹25 on ingredients for each cupcake box. During a rainy day it sells no boxes.</p></div>
<div class='questionCard'><b>Which statement is fully correct?</b><div class='answers'><button class='ans q' data-v='full'>Rent and insurance are fixed costs; ingredient cost is variable; TC at zero output still includes fixed cost.</button><button class='ans q' data-v='wrong1'>All costs become zero because output is zero.</button><button class='ans q' data-v='wrong2'>Ingredients are fixed because the stall usually needs them.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='finish')m.innerHTML=`
<div class='eyebrow'>Mission complete</div><h1>You can now separate the costs that stay from the costs that move.</h1>
<div class='coverageStrip'><p>✓ Short run &nbsp; ✓ Total fixed cost &nbsp; ✓ Total variable cost &nbsp; ✓ Total cost &nbsp; ✓ TFC, TVC and TC curves</p></div>
<p class='big'>Next: cost per unit and the cost of producing <em>one more</em> unit.</p><a class='btn primary' href='cost.html'>Back to Cost & Revenue map →</a>`;
if(t==='fixed')quiz('permit','Exactly. The permit or loan must still be paid even at zero output.','The correct answer must be a cost that remains even when nothing is produced.');if(t==='variable')quiz('ingredients','Correct. Ingredients rise as more burgers are made, so they are variable cost.','Look carefully at the economic relationship being tested.');if(t==='tableBuild')quiz('850','Correct. TC = 400 + 450 = ₹850.','Add fixed and variable cost. Total cost includes both.');if(t==='compare')quiz('rentflour','Yes. Rent stays the same over the period, while flour rises with production.','Look carefully at the economic relationship being tested.');if(t==='graphMatch')quiz('C','Correct. Total fixed cost remains constant at every output level, so its curve is horizontal.','Look carefully at the economic relationship being tested.');if(t==='board')quiz('definition','Exactly. The answer earns marks by giving the meaning clearly before the example.','Look carefully at the economic relationship being tested.');if(t==='boss')quiz('full','Boss cleared. Zero output removes variable cost, not fixed cost.','Look carefully at the economic relationship being tested.');

if(t==='iscCase')quiz('correct','Correct. Zero output does not eliminate costs that are fixed for the period, but it removes the variable ingredient cost associated with production.','Look at the economic clue, then apply the definition.');save();header()}
render();
