const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-3'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=['hook','averageIdea','afc','avc','ac','mc','mcPractice','tableAll','graphPack','compare','board','boss','finish'];
const labels={'hook':'Cost per unit','averageIdea':'What does average mean?','afc':'AFC falls','avc':'Average variable cost','ac':'Average cost','mc':'Marginal cost','mcPractice':'Find MC','tableAll':'Complete the table','graphPack':'How the curves look','compare':'One table, four meanings','board':'Board answer','boss':'Average and marginal boss','finish':'Mission complete'};
const help={'hook':'Average costs tell us cost per unit. Marginal cost tells us the cost of the next extra unit.','averageIdea':'Average means total divided by number of units.','afc':'AFC falls because the same fixed cost is spread over more units.','avc':'AVC is variable cost per unit, so divide TVC by output.','ac':'Average cost is the full cost per unit, so it includes both fixed and variable cost.','mc':'Marginal cost is the addition to total cost from producing one more unit.','mcPractice':'Subtract the old total cost from the new total cost.','tableAll':'Use each formula carefully: AFC=TFC/Q, AVC=TVC/Q, AC=TC/Q, MC = change in TC.','graphPack':'AFC keeps falling, while AVC, AC and MC typically fall first and then rise.','compare':'Attach each term to the question it answers.','board':'Use the formula and the meaning together.','boss':'Use the formulas carefully and keep “per unit” separate from “next unit”.','finish':'You can now move from cost per unit to how the curves behave and interact.'};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look carefully at the economic relationship being tested.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};
$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`
<div class='eyebrow'>Cost & Revenue • Mission 3</div><h1>Average and Marginal Cost</h1>
<div class='scene'><div class='sceneTitle'>You made 20 pizzas.</div><p>Total cost matters, but firms also ask: <b>what is cost per pizza?</b> and <b>how much did the 21st pizza add?</b></p></div>
<div class='conceptStrip'><div><b>AFC</b><span>Fixed cost per unit</span></div><div><b>AVC / AC</b><span>Variable and total cost per unit</span></div><div><b>MC</b><span>Cost of one more unit</span></div></div>`;if(t==='averageIdea')m.innerHTML=`
<div class='eyebrow'>Meaning of average cost</div><h2>What does “average cost” mean?</h2>
<div class='grid2'><div class='panel'><h3>Everyday language</h3><p>If 5 friends spend ₹500 in total, the average spending per friend is ₹100.</p></div><div class='panel'><h3>Business language</h3><p>If 10 units cost ₹1,000 in total, the average cost per unit is ₹100.</p></div></div>
<div class='equation'>Average = Total ÷ Quantity</div>
<div class='callout'>So every average cost curve is asking: <b>how much cost falls on each unit?</b></div>`;if(t==='afc')m.innerHTML=`
<div class='eyebrow'>First average curve</div><h2>Average Fixed Cost (AFC)</h2>
<div class='plotGrid'><div class='tableWrap panel'><table class='table'><tr><th>Pizzas</th><th>TFC</th><th>AFC = TFC/Q</th></tr><tr><td>1</td><td>₹1,000</td><td>₹1,000</td></tr><tr><td>10</td><td>₹1,000</td><td>₹100</td></tr><tr><td>100</td><td>₹1,000</td><td>₹10</td></tr></table></div><div class='chartwrap panel'><svg viewBox='0 0 420 260'><line x1='60' y1='20' x2='60' y2='220' class='chartAxis'/><line x1='60' y1='220' x2='390' y2='220' class='chartAxis'/><path d='M80 40 C130 100,180 145,250 175 S340 200,380 208' class='chartCurve'/><text x='8' y='28' class='chartLabel'>Cost</text><text x='300' y='250' class='chartLabel'>Output</text><text x='300' y='80' class='chartLabel'>AFC</text></svg></div></div>
<div class='definition'><div class='term'>AFC</div><p>Average fixed cost is fixed cost per unit of output.</p><div class='formal'><b>Formula:</b> AFC = TFC / Q</div></div>
<div class='questionCard'><b>Why must AFC fall as output rises?</b><div class='answers'><button class='ans q' data-v='spread'>Because the same fixed cost is spread over more units.</button><button class='ans q' data-v='ingredients'>Because ingredient prices always fall.</button><button class='ans q' data-v='zero'>Because fixed cost becomes zero.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='avc')m.innerHTML=`
<div class='eyebrow'>Second average curve</div><h2>Average Variable Cost (AVC)</h2>
<div class='grid2'><div class='panel'><h3>Idea</h3><p>Suppose variable cost of making 20 cupcakes is ₹600. Then AVC = 600 ÷ 20 = ₹30 per cupcake.</p></div><div class='definition'><div class='term'>AVC</div><p>Average variable cost is variable cost per unit of output.</p><div class='formal'><b>Formula:</b> AVC = TVC / Q</div></div></div>
<div class='callout'>AVC is about the running cost per unit: ingredients, fuel, packaging, and similar costs.</div>`;if(t==='ac')m.innerHTML=`
<div class='eyebrow'>Third average curve</div><h2>Average Cost (AC)</h2>
<div class='equation'>AC = TC / Q = AFC + AVC</div>
<div class='tableWrap panel'><table class='table'><tr><th>Output</th><th>AFC</th><th>AVC</th><th>AC</th></tr><tr><td>20</td><td>₹10</td><td>₹30</td><td>₹40</td></tr></table></div>
<div class='questionCard'><b>If AFC = ₹10 and AVC = ₹30, what is AC?</b><div class='answers'><button class='ans q' data-v='40'>₹40</button><button class='ans q' data-v='20'>₹20</button><button class='ans q' data-v='300'>₹300</button></div><div id='fb' class='feedback'></div></div>`;if(t==='mc')m.innerHTML=`
<div class='eyebrow'>Marginal cost</div><h2>Marginal Cost (MC)</h2>
<div class='grid2'><div class='panel'><h3>Question</h3><p>10 burgers cost ₹800 in total. 11 burgers cost ₹850. What did the 11th burger add?</p><div class='equation' style='font-size:34px'>₹50</div></div><div class='definition'><div class='term'>MC</div><p>Marginal cost is the addition made to total cost by producing one more unit of output.</p><div class='formal'><b>Formula:</b> MC = ΔTC / ΔQ</div></div></div>
<div class='callout'>“Marginal” always means the change caused by <b>one more</b> unit.</div>`;if(t==='mcPractice')m.innerHTML=`
<div class='eyebrow'>Quick calculation</div><h2>Find marginal cost</h2>
<div class='tableWrap panel'><table class='table'><tr><th>Output</th><th>Total Cost</th></tr><tr><td>8 units</td><td>₹720</td></tr><tr><td>9 units</td><td>₹790</td></tr></table></div>
<div class='questionCard'><b>Marginal cost of the 9th unit is:</b><div class='answers'><button class='ans q' data-v='70'>₹70</button><button class='ans q' data-v='790'>₹790</button><button class='ans q' data-v='80'>₹80</button></div><div id='fb' class='feedback'></div></div>`;if(t==='tableAll')m.innerHTML=`
<div class='eyebrow'>Table drill</div><h2>Cost table: AFC, AVC, AC and MC</h2>
<div class='tableWrap panel'><table class='table crTable'><tr><th>Q</th><th>TFC</th><th>TVC</th><th>TC</th><th>AFC</th><th>AVC</th><th>AC</th><th>MC</th></tr><tr><td>4</td><td>₹200</td><td>₹240</td><td>₹440</td><td>₹50</td><td>₹60</td><td>₹110</td><td>—</td></tr><tr><td>5</td><td>₹200</td><td>₹320</td><td>₹520</td><td>₹40</td><td>₹64</td><td>₹104</td><td>?</td></tr></table></div>
<div class='questionCard'><b>MC at output 5 is:</b><div class='answers'><button class='ans q' data-v='80'>₹80</button><button class='ans q' data-v='104'>₹104</button><button class='ans q' data-v='64'>₹64</button></div><div id='fb' class='feedback'></div></div>`;if(t==='graphPack')m.innerHTML=`
<div class='eyebrow'>Graph intuition</div><h2>What do the short-run average and marginal curves look like?</h2>
<div class='chartwrap panel'><svg viewBox='0 0 520 320'><line x1='60' y1='20' x2='60' y2='270' class='chartAxis'/><line x1='60' y1='270' x2='470' y2='270' class='chartAxis'/><path d='M95 55 C140 130,220 190,450 235' class='ghostCurve'/><path d='M90 210 C140 160,190 140,240 150 S330 210,430 245' class='chartCurve'/><path d='M90 180 C145 145,220 120,280 130 S360 180,445 220' class='secondLine budgetLine'/><path d='M85 230 C140 210,210 105,265 125 S360 230,450 265' class='budgetLine'/><text x='14' y='30' class='chartLabel'>Cost</text><text x='355' y='300' class='chartLabel'>Output</text><text x='415' y='228' class='chartLabel'>AFC</text><text x='420' y='252' class='chartLabel'>AVC</text><text x='398' y='210' class='chartLabel'>AC</text><text x='405' y='273' class='chartLabel'>MC</text></svg></div>
<div class='callout'>AFC always falls. AVC and AC are usually U-shaped. MC falls and rises faster because it tracks the extra cost of the next unit.</div>`;if(t==='compare')m.innerHTML=`
<div class='eyebrow'>Key cost relationships</div><h2>Which question does each cost answer?</h2>
<div class='grid2'><div class='panel'><b>AFC</b><p>How much fixed cost falls on each unit?</p></div><div class='panel'><b>AVC</b><p>How much variable cost falls on each unit?</p></div><div class='panel'><b>AC</b><p>What is the full cost per unit?</p></div><div class='panel'><b>MC</b><p>What did one extra unit add to cost?</p></div></div>
<div class='questionCard'><b>Which term answers “what is the cost of producing one more unit?”</b><div class='answers'><button class='ans q' data-v='MC'>MC</button><button class='ans q' data-v='AFC'>AFC</button><button class='ans q' data-v='AC'>AC</button></div><div id='fb' class='feedback'></div></div>`;if(t==='board')m.innerHTML=`
<div class='eyebrow'>Board Answer Coach</div><h2>“What is marginal cost?”</h2>
<div class='board'><p><b>Marginal cost</b> is the addition made to total cost by producing one more unit of output. It is calculated as the change in total cost divided by the change in output. For example, if total cost rises from ₹720 to ₹790 when output rises from 8 units to 9 units, marginal cost is ₹70.</p></div>
<div class='questionCard'><b>What makes this an ISC-friendly answer?</b><div class='answers'><button class='ans q' data-v='both'>It gives the meaning, the formula idea, and a simple example.</button><button class='ans q' data-v='formulaonly'>Only the formula matters.</button><button class='ans q' data-v='exampleonly'>Only the example matters.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='boss')m.innerHTML=`
<div class='eyebrow'>Comprehensive Practice</div><h2>The sandwich kiosk</h2>
<div class='caseFile'><b>CASE</b><p>A sandwich kiosk has TFC = ₹300. At output 6, TVC = ₹420. At output 7, TVC = ₹500.</p></div>
<div class='questionCard'><b>Which statement is correct?</b><div class='answers'><button class='ans q' data-v='full'>At output 6, AFC = ₹50 and AC = ₹120; MC of the 7th unit is ₹80.</button><button class='ans q' data-v='wrong1'>At output 6, AFC = ₹300 and MC of the 7th unit is ₹500.</button><button class='ans q' data-v='wrong2'>At output 6, AC = ₹70 because only TVC matters.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='finish')m.innerHTML=`
<div class='eyebrow'>Mission complete</div><h1>You now understand cost per unit and the cost of the next unit.</h1>
<div class='coverageStrip'><p>✓ AFC &nbsp; ✓ AVC &nbsp; ✓ AC &nbsp; ✓ MC &nbsp; ✓ basic calculations &nbsp; ✓ curve intuition</p></div>
<p class='big'>Next: why these curves fall, rise, and meet where they do.</p><a class='btn primary' href='cost.html'>Back to Cost & Revenue map →</a>`;
if(t==='afc')quiz('spread','Correct. TFC stays the same, so dividing it by a larger quantity makes AFC smaller.','Look carefully at the economic relationship being tested.');if(t==='ac')quiz('40','Exactly. AC = AFC + AVC = ₹40.','Look carefully at the economic relationship being tested.');if(t==='mcPractice')quiz('70','Correct. MC = 790 − 720 = ₹70.','Look carefully at the economic relationship being tested.');if(t==='tableAll')quiz('80','Yes. MC is the change in TC from 440 to 520, so MC = ₹80.','Look carefully at the economic relationship being tested.');if(t==='compare')quiz('MC','Correct. Marginal cost always focuses on the additional cost of the next unit.','Look carefully at the economic relationship being tested.');if(t==='board')quiz('both','Exactly. Meaning + formula + example is a strong exam answer.','Look carefully at the economic relationship being tested.');if(t==='boss')quiz('full','Correct. TC at 6 = 720, so AFC = 300/6 = 50 and AC = 720/6 = 120. MC of the 7th unit = 500 − 420 = 80.','Look carefully at the economic relationship being tested.');
save();header()}
render();
