const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-5'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=['hook','longRun','plants','lac','lmc','economies','diseconomies','uShape','numerical','board','boss','finish'];
const labels={'hook':'The long run','longRun':'Short run vs long run','plants':'Three plant sizes','lac':'LAC envelope','lmc':'LMC','economies':'Economies of scale','diseconomies':'Diseconomies of scale','uShape':'Why LAC is U-shaped','numerical':'Choose the right plant','board':'Board answer','boss':'Long-run boss','finish':'Mission complete'};
const help={'hook':'In the long run the firm can change plant size and all factors are variable.','longRun':'Long run is defined by flexibility, not by a specific number of months.','plants':'Different plant sizes are cheaper at different output ranges.','lac':'LAC traces the minimum attainable cost for each output by choosing the best plant size.','lmc':'LMC is the additional cost of producing one more unit in the long run.','economies':'Economies of scale make average cost fall as the firm expands.','diseconomies':'Diseconomies of scale make average cost rise once the firm becomes too large.','uShape':'Economies pull LAC down first; diseconomies push it up later.','numerical':'The long run chooses the cheapest plant for the required output.','board':'Define economies and diseconomies clearly and contrast them.','boss':'Decide whether the clue is about flexibility, scale economies, or choosing the cheapest plant.','finish':'You are now ready to switch from cost to revenue.'};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look carefully at the economic relationship being tested.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};
$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`
<div class='eyebrow'>Cost & Revenue • Mission 5</div><h1>Build the right size</h1>
<div class='scene'><div class='sceneTitle'>Long run = choose the plant you want.</div><p>A cinema owner can build a small theatre, a medium theatre, or a huge multiplex. The question becomes: which size is cheapest for each output level?</p></div>`;if(t==='longRun')m.innerHTML=`
<div class='eyebrow'>Time concept again</div><h2>What makes the long run different?</h2>
<div class='compare'><div class='panel'><h3>Short run</h3><ul><li>At least one factor fixed</li><li>Plant size fixed</li><li>TFC exists</li></ul></div><div class='op'>VS</div><div class='panel'><h3>Long run</h3><ul><li>All factors variable</li><li>Plant size can change</li><li>Firm chooses the most suitable scale</li></ul></div></div>`;if(t==='plants')m.innerHTML=`
<div class='eyebrow'>Think like a business owner</div><h2>Different plants for different output levels</h2>
<div class='grid3'><div class='panel'><h3>Small plant</h3><p>Best when output demand is low.</p></div><div class='panel'><h3>Medium plant</h3><p>Best for medium output.</p></div><div class='panel'><h3>Large plant</h3><p>Best when output demand is high.</p></div></div>
<div class='callout'>Each plant has its own short-run average cost curve. In the long run, the firm can jump to the cheapest plant.</div>`;if(t==='lac')m.innerHTML=`
<div class='eyebrow'>The famous envelope</div><h2>Long-run Average Cost (LAC)</h2>
<div class='chartwrap panel'><svg viewBox='0 0 520 320'><line x1='60' y1='20' x2='60' y2='270' class='chartAxis'/><line x1='60' y1='270' x2='470' y2='270' class='chartAxis'/><path d='M80 220 C120 170,155 155,190 165 S240 205,255 230' class='ghostCurve'/><path d='M170 210 C220 155,260 142,300 152 S355 195,390 230' class='ghostCurve'/><path d='M280 205 C335 150,380 138,425 150 S450 200,470 240' class='ghostCurve'/><path d='M92 214 C136 178,170 160,190 165 C228 173,250 160,300 152 C340 148,390 144,430 152' class='chartCurve'/><text x='15' y='30' class='chartLabel'>Cost</text><text x='345' y='300' class='chartLabel'>Output</text><text x='355' y='110' class='chartLabel'>LAC</text><text x='110' y='238' class='chartLabel'>SAC₁</text><text x='250' y='235' class='chartLabel'>SAC₂</text><text x='400' y='238' class='chartLabel'>SAC₃</text></svg></div>
<div class='definition'><div class='term'>LAC</div><p>The LAC curve shows the least possible average cost of producing each level of output when all factors are variable.</p></div>`;if(t==='lmc')m.innerHTML=`
<div class='eyebrow'>The long-run marginal curve</div><h2>Long-run Marginal Cost (LMC)</h2>
<div class='definition'><div class='term'>LMC</div><p>LMC is the addition to long-run total cost from producing one more unit of output.</p></div>
<div class='callout'>Just like MC and AC in the short run, LMC and LAC have an average–marginal relationship: LMC cuts LAC at the minimum point of LAC.</div>
<div class='questionCard'><b>Where does LMC cut LAC?</b><div class='answers'><button class='ans q' data-v='min'>At the minimum point of LAC</button><button class='ans q' data-v='top'>At the highest point of LAC</button><button class='ans q' data-v='never'>It never cuts LAC</button></div><div id='fb' class='feedback'></div></div>`;if(t==='economies')m.innerHTML=`
<div class='eyebrow'>Why LAC falls</div><h2>Economies of scale</h2>
<div class='grid3'><div class='panel'><h3>Technical economies</h3><p>Better machinery and specialization.</p></div><div class='panel'><h3>Managerial economies</h3><p>Specialized managers handle different functions.</p></div><div class='panel'><h3>Purchasing / financial economies</h3><p>Large firms may buy in bulk or raise funds more cheaply.</p></div></div>
<div class='callout'>As these benefits grow, average cost falls with expansion.</div>`;if(t==='diseconomies')m.innerHTML=`
<div class='eyebrow'>Why LAC rises later</div><h2>Diseconomies of scale</h2>
<div class='grid3'><div class='panel'><h3>Bureaucracy</h3><p>Too many layers of management.</p></div><div class='panel'><h3>Communication problems</h3><p>Information takes longer to move.</p></div><div class='panel'><h3>Coordination issues</h3><p>Departments stop working smoothly together.</p></div></div>
<div class='callout'>Once these problems dominate, average cost rises.</div>`;if(t==='uShape')m.innerHTML=`
<div class='eyebrow'>Put it together</div><h2>Why is the LAC curve U-shaped?</h2>
<div class='chartwrap panel'><svg viewBox='0 0 460 300'><line x1='60' y1='20' x2='60' y2='250' class='chartAxis'/><line x1='60' y1='250' x2='420' y2='250' class='chartAxis'/><path d='M90 190 C145 120,210 105,260 125 S335 185,390 220' class='chartCurve'/><text x='15' y='30' class='chartLabel'>Cost</text><text x='315' y='280' class='chartLabel'>Output</text><text x='340' y='210' class='chartLabel'>LAC</text><text x='90' y='225' class='chartLabel'>economies</text><text x='300' y='105' class='chartLabel'>diseconomies</text></svg></div>`;if(t==='numerical')m.innerHTML=`
<div class='eyebrow'>Practical numerical</div><h2>Which plant should the firm use?</h2>
<div class='tableWrap panel'><table class='table'><tr><th>Output 100 units</th><th>Average cost</th></tr><tr><td>Small plant</td><td>₹18</td></tr><tr><td>Medium plant</td><td>₹15</td></tr><tr><td>Large plant</td><td>₹22</td></tr></table></div>
<div class='questionCard'><b>In the long run, which plant is most suitable for 100 units?</b><div class='answers'><button class='ans q' data-v='medium'>Medium plant</button><button class='ans q' data-v='small'>Small plant</button><button class='ans q' data-v='large'>Large plant</button></div><div id='fb' class='feedback'></div></div>`;if(t==='board')m.innerHTML=`
<div class='eyebrow'>Board Answer Coach</div><h2>“Why is the LAC curve U-shaped?”</h2>
<div class='board'><p>The LAC curve is U-shaped because at first average cost falls due to economies of scale such as technical, managerial and purchasing economies. After a point, average cost rises due to diseconomies of scale such as managerial inefficiency, communication problems and difficulties in coordination.</p></div>
<div class='questionCard'><b>The strongest feature of this answer is that it:</b><div class='answers'><button class='ans q' data-v='cause'>explains both the falling and rising portions with causes.</button><button class='ans q' data-v='shape'>only mentions the shape.</button><button class='ans q' data-v='formula'>uses a formula.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='boss')m.innerHTML=`
<div class='eyebrow'>Final Boss</div><h2>The growing bakery</h2>
<div class='caseFile'><b>CASE</b><p>A bakery expands output by installing larger ovens, hiring specialized managers and buying flour in bulk. After much further expansion, communication delays and supervision problems begin increasing average cost.</p></div>
<div class='questionCard'><b>Which interpretation is best?</b><div class='answers'><button class='ans q' data-v='full'>The fall in cost reflects economies of scale; the later rise reflects diseconomies of scale, giving LAC a U-shape.</button><button class='ans q' data-v='wrong1'>All expansion always lowers average cost forever.</button><button class='ans q' data-v='wrong2'>These are short-run fixed costs only.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='finish')m.innerHTML=`
<div class='eyebrow'>Mission complete</div><h1>You now understand long-run costs and scale.</h1>
<div class='coverageStrip'><p>✓ long run &nbsp; ✓ LAC &nbsp; ✓ LMC &nbsp; ✓ economies of scale &nbsp; ✓ diseconomies of scale</p></div>
<p class='big'>Next: revenue—how much money comes in when the firm sells its output.</p><a class='btn primary' href='cost.html'>Back to Cost & Revenue map →</a>`;
if(t==='lmc')quiz('min','Correct. The average–marginal logic is the same in the long run.','Look carefully at the economic relationship being tested.');if(t==='numerical')quiz('medium','Correct. The long run selects the plant with the lowest average cost for that output.','Look carefully at the economic relationship being tested.');if(t==='board')quiz('cause','Exactly. It explains the two halves of the U-shape rather than just naming them.','Look carefully at the economic relationship being tested.');if(t==='boss')quiz('full','Boss cleared. The story describes both economies and later diseconomies of scale.','Look carefully at the economic relationship being tested.');
save();header()}
render();
