const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'cost-4'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=['hook','efficiency','crowding','uShape','mcAc','marks','mcCuts','numerical','assertion','board','boss','finish'];
const labels={'hook':'Why curves behave that way','efficiency':'Why cost falls first','crowding':'Why cost rises later','uShape':'U-shaped curves','mcAc':'MC and AC','marks':'Marks analogy','mcCuts':'MC cuts AVC and AC','numerical':'Numerical logic','assertion':'Assertion–Reason','board':'Board answer','boss':'Curve behaviour boss','finish':'Mission complete'};
const help={'hook':'The shapes of cost curves come from how efficiently variable factors are used in the short run.','efficiency':'At low output, better use of fixed resources and specialization can reduce cost per unit.','crowding':'After a point, too much output with the same fixed factor creates crowding and inefficiency.','uShape':'The curve falls while efficiency improves and rises once inefficiency begins.','mcAc':'MC pulls AC down when it is below AC, and pushes AC up when it is above AC.','marks':'Average marks and the next test score behave like AC and MC.','mcCuts':'MC meets AVC and AC at their minimum points because of average logic.','numerical':'Compare the next unit cost with the average cost to decide the direction of AC.','assertion':'Treat the assertion and the reason separately, then decide whether the reason explains the assertion.','board':'Explain both the relationship and the reason behind it.','boss':'Use the average logic instead of trying to memorize disconnected facts.','finish':'You are now ready for long-run cost curves.'};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look carefully at the economic relationship being tested.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='cost.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};
$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`
<div class='eyebrow'>Cost & Revenue • Mission 4</div><h1>Short-run Cost Curves</h1>
<div class='scene'><div class='sceneTitle'>At first, cost per unit can fall.</div><p>Workers specialize, machines are used better, and resources are coordinated more efficiently. Later, crowding and bottlenecks push cost up.</p></div>
<div class='callout'><b>Today’s goal:</b> stop memorizing U-shapes and actually understand why they appear.</div>`;if(t==='efficiency')m.innerHTML=`
<div class='eyebrow'>First half of the U</div><h2>Why do AVC and AC fall at first?</h2>
<div class='grid3'><div class='panel'><h3>Better use of fixed plant</h3><p>The oven or machine is not sitting idle.</p></div><div class='panel'><h3>Specialization</h3><p>Workers get faster at repeated tasks.</p></div><div class='panel'><h3>Less waste</h3><p>Inputs are used more efficiently.</p></div></div>`;if(t==='crowding')m.innerHTML=`
<div class='eyebrow'>Second half of the U</div><h2>Why do AVC and AC rise later?</h2>
<div class='grid3'><div class='panel'><h3>Crowding</h3><p>Too many workers use the same kitchen or machine.</p></div><div class='panel'><h3>Bottlenecks</h3><p>Output waits on a fixed input.</p></div><div class='panel'><h3>Coordination problems</h3><p>Managing extra output becomes harder.</p></div></div>
<div class='callout'>That is why average variable and average cost are usually shown as <b>U-shaped</b>.</div>`;if(t==='uShape')m.innerHTML=`
<div class='eyebrow'>Graph intuition</div><h2>The basic U-shape</h2>
<div class='chartwrap panel'><svg viewBox='0 0 460 300'><line x1='60' y1='20' x2='60' y2='250' class='chartAxis'/><line x1='60' y1='250' x2='420' y2='250' class='chartAxis'/><path d='M90 190 C145 130,205 120,255 145 S335 200,390 228' class='chartCurve'/><text x='12' y='30' class='chartLabel'>Cost</text><text x='320' y='280' class='chartLabel'>Output</text><text x='355' y='220' class='chartLabel'>AC / AVC</text></svg></div>
<div class='miniFlow centered'><span>Low output</span><b>→</b><span>better use of resources</span><b>→</b><span>cost per unit falls</span><b>→</b><span>crowding</span><b>→</b><span>cost per unit rises</span></div>`;if(t==='mcAc')m.innerHTML=`
<div class='eyebrow'>The key relationship</div><h2>How does MC affect AC?</h2>
<div class='grid2'><div class='panel'><h3>If MC &lt; AC</h3><p>The next unit costs less than the current average, so the average falls.</p></div><div class='panel'><h3>If MC &gt; AC</h3><p>The next unit costs more than the current average, so the average rises.</p></div></div>
<div class='panel'><h3>If MC = AC</h3><p>The next unit costs exactly the same as the current average, so AC is at its minimum point.</p></div>`;if(t==='marks')m.innerHTML=`
<div class='eyebrow'>Average–marginal relationship</div><h2>Your average marks = AC. Your next test score = MC.</h2>
<div class='grid3'><div class='panel'><h3>Average = 70, next score = 90</h3><p>Average rises.</p></div><div class='panel'><h3>Average = 70, next score = 50</h3><p>Average falls.</p></div><div class='panel'><h3>Average = 70, next score = 70</h3><p>Average stays the same.</p></div></div>
<div class='callout'>Exactly the same logic explains why MC cuts AC at AC’s minimum point.</div>
<div class='questionCard'><b>If MC is below AC, what happens to AC?</b><div class='answers'><button class='ans q' data-v='falls'>AC falls</button><button class='ans q' data-v='rises'>AC rises</button><button class='ans q' data-v='same'>AC stays unchanged forever</button></div><div id='fb' class='feedback'></div></div>`;if(t==='mcCuts')m.innerHTML=`
<div class='eyebrow'>Cost-curve relationship</div><h2>Where does MC cut AVC and AC?</h2>
<div class='chartwrap panel'><svg viewBox='0 0 520 320'><line x1='60' y1='20' x2='60' y2='270' class='chartAxis'/><line x1='60' y1='270' x2='470' y2='270' class='chartAxis'/><path d='M90 210 C145 165,205 150,245 160 S335 210,430 245' class='chartCurve'/><path d='M90 180 C150 145,220 125,275 135 S365 175,445 220' class='secondLine budgetLine'/><path d='M85 245 C150 230,215 110,275 136 S365 235,450 263' class='budgetLine'/><circle cx='275' cy='136' r='6' class='chartDot'/><circle cx='245' cy='160' r='6' class='chartDot'/><text x='14' y='30' class='chartLabel'>Cost</text><text x='355' y='300' class='chartLabel'>Output</text><text x='420' y='246' class='chartLabel'>AVC</text><text x='425' y='220' class='chartLabel'>AC</text><text x='417' y='272' class='chartLabel'>MC</text></svg></div>
<div class='callout'>MC cuts <b>AVC</b> at AVC’s minimum point and cuts <b>AC</b> at AC’s minimum point.</div>`;if(t==='numerical')m.innerHTML=`
<div class='eyebrow'>Numerical thinking</div><h2>If AC = ₹40 and MC = ₹32, what must happen?</h2>
<div class='questionCard'><b>Choose the correct statement.</b><div class='answers'><button class='ans q' data-v='down'>AC will fall because MC is below AC.</button><button class='ans q' data-v='up'>AC will rise because MC is below AC.</button><button class='ans q' data-v='same'>AC must stay unchanged.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='assertion')m.innerHTML=`
<div class='eyebrow'>Exam pattern</div><h2>Assertion–Reason</h2>
<div class='paperCard'><p><b>Assertion:</b> Marginal cost cuts average cost at the latter’s minimum point.</p><p><b>Reason:</b> When marginal cost is less than average cost, average cost falls; when marginal cost is greater than average cost, average cost rises.</p></div>
<div class='questionCard'><b>Pick the best option.</b><div class='answers'><button class='ans q' data-v='both'>Both are true and the reason explains the assertion.</button><button class='ans q' data-v='truefalse'>Assertion true, reason false.</button><button class='ans q' data-v='bothno'>Both are true but the reason does not explain the assertion.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='board')m.innerHTML=`
<div class='eyebrow'>Board Answer Coach</div><h2>“State the relationship between AC and MC.”</h2>
<div class='board'><p>When marginal cost is less than average cost, average cost falls. When marginal cost is greater than average cost, average cost rises. Therefore, marginal cost cuts average cost at the minimum point of the average cost curve.</p></div>
<div class='questionCard'><b>What extra word makes the answer stronger?</b><div class='answers'><button class='ans q' data-v='therefore'>“Therefore,” because it shows the conclusion follows from the relationship.</button><button class='ans q' data-v='always'>“Always,” because it sounds confident.</button><button class='ans q' data-v='basically'>“Basically,” because it sounds casual.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='boss')m.innerHTML=`
<div class='eyebrow'>Comprehensive Practice</div><h2>Graph Application</h2>
<div class='caseFile'><b>CASE</b><p>A firm observes that the cost of producing one more unit has fallen below its current average variable cost and average cost.</p></div>
<div class='questionCard'><b>Which statement follows?</b><div class='answers'><button class='ans q' data-v='bothfall'>Both AVC and AC will tend to fall.</button><button class='ans q' data-v='rise'>Both must rise.</button><button class='ans q' data-v='nothing'>No inference can be made.</button></div><div id='fb' class='feedback'></div></div>`;if(t==='finish')m.innerHTML=`
<div class='eyebrow'>Mission complete</div><h1>You now understand the logic behind the cost curves.</h1>
<div class='coverageStrip'><p>✓ U-shapes &nbsp; ✓ why costs fall and rise &nbsp; ✓ MC–AC relationship &nbsp; ✓ MC cuts AC and AVC at their minima</p></div>
<p class='big'>Next: the long run, plant size, LAC, LMC and scale economies.</p><a class='btn primary' href='cost.html'>Back to Cost & Revenue map →</a>`;
if(t==='marks')quiz('falls','Correct. A next-unit cost below the average pulls the average down.','Look carefully at the economic relationship being tested.');if(t==='numerical')quiz('down','Exactly. MC below AC pulls the average cost down.','Look carefully at the economic relationship being tested.');if(t==='assertion')quiz('both','Correct. The reason gives the exact average logic behind the assertion.','Look carefully at the economic relationship being tested.');if(t==='board')quiz('therefore','Yes. It links the rule to the graph conclusion.','Look carefully at the economic relationship being tested.');if(t==='boss')quiz('bothfall','Correct. A marginal value below an average pulls that average down.','Look carefully at the economic relationship being tested.');
save();header()}
render();
