const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'market-5'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook", "meaning", "features", "interdependence", "console", "product", "entry", "monopsony", "monoCompare", "transfer", "specimenStyle", "board", "boss", "finish"]; const labels={"hook": "Console rivals", "meaning": "Oligopoly meaning", "features": "Features", "interdependence": "Interdependence", "console": "Reaction game", "product": "Product type", "entry": "Entry barriers", "monopsony": "Monopsony", "monoCompare": "Monopoly vs monopsony", "transfer": "ISC transfer", "specimenStyle": "Specimen-style compare", "board": "Board answer", "boss": "Boss battle", "finish": "Mission complete"}; const help={"hook": "The console story is useful because it makes \u201cfew large rivals\u201d and reaction to competitors intuitive.", "meaning": "Oligopoly means a few important sellers dominate the market. The exact number is not the definition; the small number makes firms interdependent.", "features": "Features include few sellers, entry barriers, interdependence and possibly homogeneous or differentiated products.", "interdependence": "Interdependence means one firm considers likely rival reactions before changing price, output, advertising or product strategy.", "console": "This is not about predicting real console companies. It is a simplified strategic-reaction game.", "product": "Oligopoly can sell homogeneous products or differentiated products. Do not use product differentiation alone to identify it.", "entry": "Entry barriers help keep the number of major firms small.", "monopsony": "Monopsony describes the buyer side: one buyer facing many potential sellers.", "monoCompare": "Use the word after \u201cone\u201d: one seller = monopoly; one buyer = monopsony.", "transfer": "If a question says \u201cfew large firms and each watches rivals,\u201d interdependence is the decisive clue.", "specimenStyle": "CISCE\u2019s 2025 specimen answer key contrasts monopolistic competition with oligopoly by product, entry/exit and price control.", "board": "Explain interdependence, do not merely say \u201cfew firms.\u201d", "boss": "The boss tests the buyer/seller distinction and oligopoly clue.", "finish": "Next mission combines all market forms and demand curves."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look again at the economic clue, not the brand name or story.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function finish(){save();header()}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 5</div><h1>A few console ecosystems. Every big move gets noticed.</h1><div class="photoLesson"><img src="https://upload.wikimedia.org/wikipedia/commons/c/c7/Xbox_One_consoles_montage.png" alt="Xbox consoles"><div><p class="big">Imagine one major console maker suddenly cuts price, buys an exclusive game studio, or changes subscription pricing.</p><p>Would its major rivals ignore it?</p><div class="answers"><button class="ans q" data-v="react">Probably not. Their strategy may change too.</button><button class="ans q" data-v="ignore">Yes. Rivals never care what competitors do.</button></div><div id="fb" class="feedback"></div></div></div><p class="sourceNote">Photo: Evan-Amos / Wikimedia Commons, public domain.</p>`;
else if(t==='meaning')m.innerHTML=`<div class="eyebrow">9.6 Oligopoly</div><h2>A few large sellers, each too important to ignore.</h2><div class="definition"><div class="term">ISC-ready definition</div><p><b>Oligopoly</b> is a market form in which a few large firms dominate the market and the decisions of one firm significantly affect, and are affected by, rival firms.</p></div>`;
else if(t==='features')m.innerHTML=`<div class="eyebrow">Features</div><div class="factorGrid"><div><b>🤏 Few sellers</b><span>Each controls a meaningful share.</span></div><div><b>👀 Interdependence</b><span>Firms consider rival reactions.</span></div><div><b>🧱 Entry barriers</b><span>New large rivals are difficult to establish.</span></div><div><b>📦 Product can vary</b><span>Homogeneous or differentiated.</span></div><div><b>📣 Non-price competition</b><span>Branding, features and promotion can matter strongly.</span></div><div><b>💸 Substantial price influence</b><span>But strategy is constrained by rivals.</span></div></div>`;
else if(t==='interdependence')m.innerHTML=`<div class="eyebrow">The signature clue</div><h2>Interdependence = “I move, you react, so I think about your reaction first.”</h2><div class="rivalDiagram"><div class="rivalFirm">Firm A<br><small>cuts price</small></div><div class="reactionArrow">→ watches →</div><div class="rivalFirm">Firm B<br><small>responds?</small></div><div class="reactionArrow">↘</div><div class="rivalFirm">Firm C<br><small>changes strategy?</small></div></div>`;
else if(t==='console')m.innerHTML=`<div class="eyebrow">Mini strategy game</div><h2>You run Console A.</h2><div class="caseFile"><p>Console B launches a cheaper subscription that includes several major games.</p></div><div class="answers"><button class="ans q" data-v="consider">Before acting, consider how matching, ignoring or differentiating will affect B and C.</button><button class="ans q" data-v="independent">Pretend competitors do not exist because your decisions are independent.</button></div><div id="fb" class="feedback"></div>`;
else if(t==='product')m.innerHTML=`<div class="eyebrow">Don't overlearn one clue</div><h2>Oligopoly products may be homogeneous OR differentiated.</h2><div class="visualCompare"><div class="visualPanel"><b>Homogeneous oligopoly</b><p>A few firms selling a largely standardized industrial product.</p></div><div class="visualPanel"><b>Differentiated oligopoly</b><p>A few firms selling branded products with meaningful differences.</p></div></div><div class="notice">So the strongest diagnostic clue is usually <b>few firms + interdependence</b>.</div>`;
else if(t==='entry')m.innerHTML=`<div class="eyebrow">Why only a few?</div><h2>Entry can require enormous scale, technology, distribution or brand investment.</h2><div class="barrierWall"><div>💰 High capital requirement</div><div>🧠 Technology / patents</div><div>🌐 Network/ecosystem advantage</div><div>🏷️ Established brands</div></div>`;
else if(t==='monopsony')m.innerHTML=`<div class="eyebrow">9.7 Monopsony</div><h2>Now flip the market around.</h2><div class="buyerFunnel"><div class="manySellers">👩‍💼 👨‍💼 👩‍💼 👨‍💼 👩‍💼<br><small>many sellers of labour</small></div><div class="funnelArrow">↓↓↓</div><div class="oneBuyer">🏭 ONE major buyer / employer</div></div><div class="definition"><div class="term">ISC-ready definition</div><p><b>Monopsony</b> is a market situation in which there is a single buyer of a commodity or factor service.</p></div>`;
else if(t==='monoCompare')m.innerHTML=`<div class="eyebrow">Memory repair</div><h2>Monopoly vs monopsony</h2><div class="tableWrap"><table class="table"><thead><tr><th></th><th>Monopoly</th><th>Monopsony</th></tr></thead><tbody><tr><td>The “one” is...</td><td>ONE SELLER</td><td>ONE BUYER</td></tr><tr><td>Power sits mainly with...</td><td>Seller</td><td>Buyer</td></tr><tr><td>Simple picture</td><td>1 seller → many buyers</td><td>many sellers → 1 buyer</td></tr></tbody></table></div>`;
else if(t==='transfer')m.innerHTML=`<div class="eyebrow">ISC transfer</div><h2>Identify the decisive clue.</h2><div class="caseFile"><p>Four major firms supply most of a product. When one changes its price, the others quickly review their own prices and promotion.</p></div><div class="answers"><button class="ans q" data-v="ol">Oligopoly: few firms and mutual interdependence</button><button class="ans q" data-v="mc">Monopolistic competition: many independent sellers</button><button class="ans q" data-v="mo">Monopoly: one seller</button></div><div id="fb" class="feedback"></div>`;
else if(t==='specimenStyle')m.innerHTML=`<div class="eyebrow">Specimen-style compare</div><h2>Monopolistic competition vs oligopoly</h2><div class="tableWrap"><table class="table"><thead><tr><th>Basis</th><th>Monopolistic competition</th><th>Oligopoly</th></tr></thead><tbody><tr><td>Product</td><td>Differentiated</td><td>Homogeneous or differentiated</td></tr><tr><td>Entry & exit</td><td>Relatively free</td><td>Restricted / difficult</td></tr><tr><td>Price control</td><td>Some/fair control over own differentiated product</td><td>Substantial, but constrained by rival reactions</td></tr></tbody></table></div><div class="notice">CISCE’s 2025 specimen answer key uses these bases of comparison.</div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board answer</div><h2>Why are firms under oligopoly interdependent?</h2><div class="board"><p>There are only a few large firms under oligopoly, and each controls a significant share of the market. Therefore a change in price, output, advertising or product strategy by one firm can materially affect the sales and profits of rival firms. Each firm must consequently take expected rival reactions into account while making decisions. This mutual dependence is called <b>interdependence</b>.</p></div>`;
else if(t==='boss')m.innerHTML=`<div class="eyebrow">Boss battle</div><h2>A town has hundreds of workers but only one company buys their specialised labour. What is it?</h2><div class="answers"><button class="ans q" data-v="mp">Monopsony</button><button class="ans q" data-v="mo">Monopoly</button><button class="ans q" data-v="ol">Oligopoly</button></div><div id="fb" class="feedback"></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>Few-firm strategy unlocked.</h1><a class="btn primary" href="mission.html?mission=market-6">Final mission: Curves, comparisons & exam boss →</a>`;
if(t==='hook')quiz('react','Exactly. Strategic reaction is the intuition behind interdependence.');if(t==='console')quiz('consider','Correct. A few important rivals make strategic decisions interdependent.');if(t==='transfer')quiz('ol','Correct. “Few major firms” plus rapid rival reaction is classic oligopoly logic.');if(t==='boss')quiz('mp','Correct. The “one” is the buyer, so this is monopsony.');finish()}
render();