const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'market-6'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook", "allCurves", "pcCurve", "monoCurve", "mcCurve", "oligoCaution", "master", "curveMatch", "spotClue", "pyq1", "pyq2", "assertion", "boardCompare", "boss1", "boss2", "finish"]; const labels={"hook": "Curve detective", "allCurves": "All market forms", "pcCurve": "Perfect competition curve", "monoCurve": "Monopoly curve", "mcCurve": "Monopolistic curve", "oligoCaution": "Oligopoly caution", "master": "Master comparison", "curveMatch": "Match the curve", "spotClue": "Spot the clue", "pyq1": "ISC-style case 1", "pyq2": "ISC-style case 2", "assertion": "Assertion & reason", "boardCompare": "Board comparison", "boss1": "Boss: classify", "boss2": "Boss: explain", "finish": "Chapter complete"}; const help={"hook": "The chapter ends by connecting market structure to the demand curve facing a firm.", "allCurves": "The key contrast is fixed market price for one perfect-competition firm versus downward-sloping demand when a firm has some price discretion.", "pcCurve": "Horizontal does not mean market demand is horizontal. It is the demand facing one tiny firm at the market price.", "monoCurve": "A monopoly is the sole seller and therefore faces the market demand curve.", "mcCurve": "Differentiated products give a monopolistically competitive firm some price discretion, so its demand curve slopes downward.", "oligoCaution": "Do not invent one universal oligopoly curve unless your prescribed treatment explicitly asks for a particular model. Oligopoly demand depends on rival reactions.", "master": "This table is your final chapter map. Read across one row at a time.", "curveMatch": "Match the graph to the economic reason, not just the shape.", "spotClue": "The fastest exam method is to underline structural clues in the question.", "pyq1": "This is inspired by recent CISCE market-identification style, not copied verbatim.", "pyq2": "This comparison follows the exact kinds of bases CISCE marking material rewards.", "assertion": "Assertion-reason questions punish vague memorization. Check truth first, then whether the reason explains the assertion.", "boardCompare": "Use common bases and complete sentences when differentiating market forms.", "boss1": "Mixed classification forces you to choose among all forms.", "boss2": "A \u201cwhy\u201d answer needs a causal chain.", "finish": "Every numbered chapter topic is now represented across the six missions."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look again at the economic clue, not the brand name or story.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function finish(){save();header()}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 6</div><h1>Can you look at a curve and tell me what market power caused it?</h1><div class="visualCompare"><div class="visualPanel"><div class="miniCurve horizontalCurve"></div><b>Horizontal</b><p>One perfectly competitive firm</p></div><div class="visualPanel"><div class="miniCurve fallingCurve"></div><b>Downward sloping</b><p>Firm has some price discretion</p></div></div>`;
else if(t==='allCurves')m.innerHTML=`<div class="eyebrow">9.8 Firm demand curves</div><h2>Market structure changes the demand facing one firm.</h2><div class="tableWrap"><table class="table"><thead><tr><th>Market form</th><th>Demand/AR facing firm</th><th>Why?</th></tr></thead><tbody><tr><td>Perfect competition</td><td>Perfectly elastic / horizontal</td><td>Firm is a price taker at market price.</td></tr><tr><td>Monopoly</td><td>Downward sloping</td><td>Sole seller faces market demand.</td></tr><tr><td>Monopolistic competition</td><td>Downward sloping</td><td>Differentiation gives some price control; close substitutes remain.</td></tr><tr><td>Oligopoly</td><td>Depends on rival reaction/model</td><td>Interdependence makes demand behaviour strategic.</td></tr></tbody></table></div>`;
else if(t==='pcCurve')m.innerHTML=`<div class="eyebrow">Perfect competition</div><h2>One firm cannot choose its own price.</h2><div class="graphExplain"><svg viewBox="0 0 620 330" role="img" aria-label="Horizontal demand curve of a perfectly competitive firm"><line x1="70" y1="280" x2="585" y2="280" class="chartAxis"/><line x1="70" y1="280" x2="70" y2="35" class="chartAxis"/><g class="chartGrid"><line x1="70" y1="220" x2="585" y2="220"/><line x1="70" y1="160" x2="585" y2="160"/><line x1="70" y1="100" x2="585" y2="100"/></g><line x1="85" y1="160" x2="565" y2="160" class="marketCurve pcLine"/><text x="500" y="145" class="chartLabel">AR = MR = Price</text><text x="15" y="55" class="chartLabel">Price</text><text x="505" y="315" class="chartLabel">Quantity</text><circle cx="175" cy="160" r="7" class="chartDot"/><circle cx="330" cy="160" r="7" class="chartDot"/><circle cx="485" cy="160" r="7" class="chartDot"/></svg><div class="notice"><b>Read it:</b> the firm can change quantity sold while the market price stays the same. That is why its demand/AR curve is horizontal.</div></div>`;
else if(t==='monoCurve')m.innerHTML=`<div class="eyebrow">Monopoly</div><h2>The sole seller faces market demand.</h2><div class="graphExplain"><svg viewBox="0 0 620 330" role="img" aria-label="Downward sloping demand curve"><line x1="70" y1="280" x2="585" y2="280" class="chartAxis"/><line x1="70" y1="280" x2="70" y2="35" class="chartAxis"/><g class="chartGrid"><line x1="70" y1="220" x2="585" y2="220"/><line x1="70" y1="160" x2="585" y2="160"/><line x1="70" y1="100" x2="585" y2="100"/></g><path d="M110 80 C240 120 390 190 550 255" class="marketCurve downLine"/><text x="470" y="235" class="chartLabel">AR / Demand</text><text x="15" y="55" class="chartLabel">Price</text><text x="505" y="315" class="chartLabel">Quantity</text></svg><div class="notice"><b>Read it:</b> to sell more, the firm generally has to accept a lower price. So its demand/AR curve slopes downward.</div></div><div class="notice">AR slopes downward; MR lies below AR when the firm lowers price to sell more. Revenue relationships are developed fully in the Cost & Revenue chapter.</div>`;
else if(t==='mcCurve')m.innerHTML=`<div class="eyebrow">Monopolistic competition</div><h2>Brand differentiation gives some price discretion.</h2><div class="graphExplain"><svg viewBox="0 0 620 330" role="img" aria-label="Downward sloping demand curve"><line x1="70" y1="280" x2="585" y2="280" class="chartAxis"/><line x1="70" y1="280" x2="70" y2="35" class="chartAxis"/><g class="chartGrid"><line x1="70" y1="220" x2="585" y2="220"/><line x1="70" y1="160" x2="585" y2="160"/><line x1="70" y1="100" x2="585" y2="100"/></g><path d="M110 80 C240 120 390 190 550 255" class="marketCurve downLine"/><text x="470" y="235" class="chartLabel">AR / Demand</text><text x="15" y="55" class="chartLabel">Price</text><text x="505" y="315" class="chartLabel">Quantity</text></svg><div class="notice"><b>Read it:</b> to sell more, the firm generally has to accept a lower price. So its demand/AR curve slopes downward.</div></div><div class="notice">The curve is downward sloping, but close substitutes make buyers relatively responsive compared with a strong monopoly.</div>`;
else if(t==='oligoCaution')m.innerHTML=`<div class="eyebrow">Oligopoly</div><h2>Why we don't slap one universal curve on it.</h2><div class="rivalDiagram"><div class="rivalFirm">Your price change</div><div class="reactionArrow">→</div><div class="rivalFirm">Rivals may match</div><div class="reactionArrow">or</div><div class="rivalFirm">Rivals may not match</div></div><div class="callout">Because firms are interdependent, the demand facing an oligopolist depends on assumptions about rival reactions. Learn the specific curve model only if your textbook/teacher explicitly requires it.</div>`;
else if(t==='master')m.innerHTML=`<div class="eyebrow">9.9 Comparison overview</div><h2>The whole chapter on one screen.</h2><div class="tableWrap"><table class="table marketTable"><thead><tr><th>Basis</th><th>Perfect competition</th><th>Monopolistic competition</th><th>Oligopoly</th><th>Monopoly</th><th>Monopsony</th></tr></thead><tbody><tr><td>Sellers</td><td>Very many</td><td>Many</td><td>Few</td><td>One</td><td>May be many</td></tr><tr><td>Buyer side</td><td>Many</td><td>Many</td><td>Many</td><td>Many</td><td><b>One buyer</b></td></tr><tr><td>Product</td><td>Homogeneous</td><td>Differentiated</td><td>Homogeneous or differentiated</td><td>No close substitute</td><td>Varies</td></tr><tr><td>Entry</td><td>Free</td><td>Relatively free</td><td>Restricted</td><td>Restricted</td><td>Buyer-side concentration</td></tr><tr><td>Price power</td><td>None/very little</td><td>Some</td><td>Substantial, strategic</td><td>High</td><td>Buyer power</td></tr><tr><td>Signature clue</td><td>Price taker</td><td>Differentiation</td><td>Interdependence</td><td>Single seller</td><td>Single buyer</td></tr></tbody></table></div>`;
else if(t==='curveMatch')m.innerHTML=`<div class="eyebrow">Graph detective</div><h2>A firm can sell additional units only by lowering its own price. Which market CANNOT fit that description?</h2><div class="answers"><button class="ans q" data-v="pc">Perfect competition</button><button class="ans q" data-v="mo">Monopoly</button><button class="ans q" data-v="mc">Monopolistic competition</button></div><div id="fb" class="feedback"></div>`;
else if(t==='spotClue')m.innerHTML=`<div class="eyebrow">Spot the clue</div><h2>Which phrase screams oligopoly?</h2><div class="caseFile"><p>“There are <mark>four major producers</mark>. A promotional campaign by one firm is usually followed by <mark>counter-campaigns from its rivals</mark>.”</p></div><div class="answers"><button class="ans q" data-v="inter">Few firms + rival reactions</button><button class="ans q" data-v="price">The product has a price</button><button class="ans q" data-v="buyers">There are customers</button></div><div id="fb" class="feedback"></div>`;
else if(t==='pyq1')m.innerHTML=`<div class="eyebrow">ISC-style case</div><h2>A sole producer sells at different prices in two places.</h2><div class="caseFile"><p>A producer is the only seller of a product and charges a higher price in Market A than Market B, where buyers are more responsive to price.</p></div><div class="answers"><button class="ans q" data-v="mo">Monopoly</button><button class="ans q" data-v="ol">Oligopoly</button><button class="ans q" data-v="mp">Monopsony</button></div><div id="fb" class="feedback"></div><p class="sourceNote">Inspired by a CISCE specimen question about a sole AC producer selling in Delhi and Mussoorie.</p>`;
else if(t==='pyq2')m.innerHTML=`<div class="eyebrow">ISC-style comparison</div><h2>Which difference is valid?</h2><div class="answers"><button class="ans q" data-v="entry">Monopolistic competition has relatively free entry; oligopoly has restricted entry.</button><button class="ans q" data-v="same">Both always have identical products and no price control.</button><button class="ans q" data-v="one">Oligopoly always has exactly one seller.</button></div><div id="fb" class="feedback"></div>`;
else if(t==='assertion')m.innerHTML=`<div class="eyebrow">Assertion & Reason</div><h2>Reason it out.</h2><div class="caseFile"><p><b>Assertion:</b> A perfectly competitive firm is a price taker.<br><b>Reason:</b> It is one of very many sellers offering a homogeneous product, so charging above market price causes buyers to switch.</p></div><div class="answers"><button class="ans q" data-v="explain">Both are true and the Reason correctly explains the Assertion.</button><button class="ans q" data-v="not">Both are true but the Reason does not explain the Assertion.</button><button class="ans q" data-v="false">The Assertion is false.</button></div><div id="fb" class="feedback"></div>`;
else if(t==='boardCompare')m.innerHTML=`<div class="eyebrow">Board answer builder</div><h2>Compare monopoly and perfect competition.</h2><div class="tableWrap"><table class="table"><thead><tr><th>Basis</th><th>Perfect competition</th><th>Monopoly</th></tr></thead><tbody><tr><td>Number of sellers</td><td>Very large number</td><td>Single seller</td></tr><tr><td>Nature of product</td><td>Homogeneous</td><td>No close substitute</td></tr><tr><td>Entry</td><td>Free entry and exit</td><td>Restricted by barriers</td></tr><tr><td>Price influence</td><td>Price taker</td><td>Price maker / substantial control</td></tr><tr><td>Firm demand</td><td>Horizontal / perfectly elastic</td><td>Downward sloping</td></tr></tbody></table></div><div class="callout">Write differences using a <b>common basis</b> and complete statements.</div>`;
else if(t==='boss1')m.innerHTML=`<div class="eyebrow">Final boss • 1/2</div><h2>Many sellers. Differentiated products. Advertising matters. Relatively free entry.</h2><div class="answers"><button class="ans q" data-v="mc">Monopolistic competition</button><button class="ans q" data-v="pc">Perfect competition</button><button class="ans q" data-v="ol">Oligopoly</button></div><div id="fb" class="feedback"></div>`;
else if(t==='boss2')m.innerHTML=`<div class="eyebrow">Final boss • 2/2</div><h2>Why is the firm's demand curve horizontal under perfect competition?</h2><div class="answers"><button class="ans q" data-v="logic">The firm is a tiny price taker selling a homogeneous product at a market-given price.</button><button class="ans q" data-v="one">Because there is one seller.</button><button class="ans q" data-v="brand">Because products are heavily differentiated.</button></div><div id="fb" class="feedback"></div>`;
else m.innerHTML=`<div class="eyebrow">Chapter complete</div><h1>Forms of Market cleared. 🏆</h1><p class="big">You covered the concept of market, market structure, determining factors, classification, perfect competition, pure vs perfect competition, monopoly, monopolistic competition, oligopoly, monopsony, firm demand curves and the final comparison.</p><div class="actions"><a class="btn primary" href="market.html">Forms of Market map</a><a class="btn secondary" href="menu.html">Course menu</a></div>`;
if(t==='curveMatch')quiz('pc','Correct. A perfectly competitive firm takes a fixed market price, so its own demand/AR curve is horizontal.');if(t==='spotClue')quiz('inter','Correct. Few firms + reciprocal strategic reaction = oligopoly.');if(t==='pyq1')quiz('mo','Correct. “Only seller” identifies monopoly.');if(t==='pyq2')quiz('entry','Correct. CISCE specimen marking material uses entry restrictions as one valid basis of contrast.');if(t==='assertion')quiz('explain','Correct. The reason directly explains why the firm lacks price control.');if(t==='boss1')quiz('mc','Correct. Those are the classic clues of monopolistic competition.');if(t==='boss2')quiz('logic','Correct. Many sellers + homogeneous product + market-given price produce a perfectly elastic firm demand curve.');finish()}
render();