const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'market-4'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook", "cinemaScene", "racketScene", "meaning", "features", "differentiate", "tennis", "sellingCosts", "entry", "pricePower", "graph", "comparePc", "transfer", "board", "boss", "finish"]; const labels={"hook": "Choose your racket", "meaning": "Meaning", "features": "Features", "differentiate": "Product differentiation", "tennis": "Tennis brands", "sellingCosts": "Selling costs", "entry": "Entry and exit", "pricePower": "Some price power", "graph": "Demand curve", "comparePc": "vs perfect competition", "transfer": "ISC transfer", "board": "Board answer", "boss": "Boss battle", "finish": "Mission complete", "cinemaScene": "Movie theatre market", "racketScene": "Tennis racket market"}; const help={"hook": "The point is not that every racket is completely different. It is that buyers perceive meaningful differences between brands/models.", "meaning": "Monopolistic competition combines \u201cmany sellers\u201d with \u201cdifferentiated products.\u201d", "features": "The market is competitive because there are many firms, but each brand has a small pocket of market power.", "differentiate": "Differentiation can come from quality, design, location, service, packaging, reputation or branding.", "tennis": "Tennis-racket brands are a familiar intuition example, not a claim that the global racket industry perfectly satisfies every textbook condition.", "sellingCosts": "Selling costs are expenditures intended to persuade buyers or differentiate the product, such as advertising and promotion.", "entry": "Entry is relatively free compared with monopoly/oligopoly, which limits long-term protected power.", "pricePower": "Brand loyalty means a small price increase may not make every customer leave immediately.", "graph": "The firm demand curve slopes downward because it can vary its own price, but substitutes from rival brands make demand comparatively elastic.", "comparePc": "The best comparison uses a common basis: product, price influence, AR/MR or demand curve.", "transfer": "Fresh context tests whether you can recognize differentiated products rather than memorizing restaurants.", "board": "ISC comparisons should be written on the same basis for both market forms.", "boss": "The 2025 specimen answer key compares monopolistic competition and oligopoly by product type, entry and price control.", "finish": "Next: few-firm markets and strategic reactions.", "cinemaScene": "Many cinemas sell the same broad service but differ by location, seats, screens, food, memberships and experience. That can create loyalty.", "racketScene": "Racket brands serve the same broad purpose but are not identical in buyers' eyes. Feel, specifications, reputation and branding create product differentiation."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look again at the economic clue, not the brand name or story.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function finish(){save();header()}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 4</div><h1>You need a tennis racket.</h1><div class="photoLesson"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Tennis_racket_and_ball.JPG/960px-Tennis_racket_and_ball.JPG" alt="Tennis racket and ball"><div><p class="big">Would you treat every racket from every brand and model as exactly identical?</p><div class="answers"><button class="ans q" data-v="different">No. Brand, feel, design and reputation can matter.</button><button class="ans q" data-v="same">Yes. Every racket is economically identical.</button></div><div id="fb" class="feedback"></div></div></div><p class="sourceNote">Photo: nao2g / Wikimedia Commons, CC BY 3.0.</p>`;
else if(t==='cinemaScene')m.innerHTML=`<div class="eyebrow">Start from your surroundings</div><h2>You want to see a movie. Are all theatres identical to you?</h2><div class="cinemaChoices"><div><b>🎬 Theatre A</b><span>closest to home</span><small>₹ ticket</small></div><div><b>🍿 Theatre B</b><span>better seats + food</span><small>₹₹ ticket</small></div><div><b>🔊 Theatre C</b><span>premium screen/sound</span><small>₹₹₹ ticket</small></div></div><div class="fourLens"><div><b>🙋 Buyers</b><span>Moviegoers</span></div><div><b>🏢 Sellers</b><span>Cinema businesses</span></div><div><b>📦 Exchange</b><span>Movie-going experience</span></div><div><b>🌍 Situation</b><span>Many sellers, but offerings differ</span></div></div><div class="notice">Preference for one theatre can give that seller <b>some</b> price discretion.</div>`;
else if(t==='racketScene')m.innerHTML=`<div class="eyebrow">Another familiar market</div><h2>Wilson, Babolat, Head and Yonex all sell tennis rackets. Why don't they all charge one identical price?</h2><div class="brandShelf"><div>🎾<b>Racket A</b><span>feel / weight</span></div><div>🎾<b>Racket B</b><span>spin / control</span></div><div>🎾<b>Racket C</b><span>brand / preference</span></div><div>🎾<b>Racket D</b><span>design / specs</span></div></div><div class="questionCard"><b>What matters economically?</b><div class="answers"><button class="ans q" data-v="diff">Buyers perceive meaningful differences between brands.</button><button class="ans q" data-v="same">Every racket is homogeneous in buyers' eyes.</button></div><div id="fb" class="feedback"></div></div><div class="notice">This is the intuition behind <b>product differentiation</b>. Real industries need not fit textbook models perfectly.</div>`;
else if(t==='meaning')m.innerHTML=`<div class="eyebrow">9.5 Monopolistic Competition</div><h2>Many sellers, but not identical products.</h2><div class="definition"><div class="term">ISC-ready definition</div><p><b>Monopolistic competition</b> is a market form in which a large number of firms sell differentiated products that are close substitutes.</p></div>`;
else if(t==='features')m.innerHTML=`<div class="eyebrow">Features</div><div class="factorGrid"><div><b>👥 Large number of sellers</b><span>No single firm dominates the whole market.</span></div><div><b>🎨 Product differentiation</b><span>Brands/products are perceived as different.</span></div><div><b>🚪 Relatively free entry & exit</b><span>New rivals can enter more easily than under monopoly.</span></div><div><b>📣 Selling costs</b><span>Advertising and promotion matter.</span></div><div><b>💸 Some price control</b><span>Brand loyalty gives limited influence.</span></div><div><b>🔁 Close substitutes</b><span>Customers can switch to rival brands.</span></div></div>`;
else if(t==='differentiate')m.innerHTML=`<div class="eyebrow">The signature feature</div><h2>Product differentiation = “same broad need, meaningfully different offer.”</h2><div class="diagramRow"><div class="diagramPill">Quality</div><div class="diagramPill">Design</div><div class="diagramPill">Location</div><div class="diagramPill">Service</div><div class="diagramPill">Brand</div><div class="diagramPill">Packaging</div></div><div class="questionCard"><b>Which is the best example of differentiation?</b><div class="answers"><button class="ans q" data-v="brand">Two cinemas show the same film but differ in location, seats, sound and experience.</button><button class="ans q" data-v="identical">Two sellers offer an identical standardized commodity with no perceived difference.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='tennis')m.innerHTML=`<div class="eyebrow">Use your world</div><h2>Why can one racket brand charge differently?</h2><div class="causeChain"><div><b>Perceived differences</b><span>feel, technology, athlete association, design</span></div><div class="chainArrow">→</div><div><b>Brand preference</b><span>some buyers prefer one option</span></div><div class="chainArrow">→</div><div><b>Some price influence</b><span>but rival brands remain substitutes</span></div></div><div class="callout">This is the intuition behind monopolistic competition. In an exam, use the features stated in the question rather than assuming every real sports market perfectly fits the model.</div>`;
else if(t==='sellingCosts')m.innerHTML=`<div class="eyebrow">Selling costs</div><h2>Firms spend money to make their version feel different.</h2><div class="worldGrid"><div class="worldCard"><div class="emojiHero">📺</div><b>Advertising</b><p>Make buyers aware of the brand.</p></div><div class="worldCard"><div class="emojiHero">🎾⭐</div><b>Endorsements</b><p>Connect product with players or identity.</p></div><div class="worldCard"><div class="emojiHero">🏬</div><b>Store experience</b><p>Service and presentation can differentiate.</p></div></div><div class="definition"><div class="term">Selling costs</div><p>Expenditure incurred to promote sales, influence buyers or differentiate a firm's product, such as advertising and sales promotion.</p></div>`;
else if(t==='entry')m.innerHTML=`<div class="eyebrow">Entry and exit</div><h2>Successful ideas attract imitators and new brands.</h2><div class="causeChain"><div><b>Firm finds profitable niche</b></div><div class="chainArrow">→</div><div><b>Other firms can enter relatively freely</b></div><div class="chainArrow">→</div><div><b>Competition limits protected power</b></div></div>`;
else if(t==='pricePower')m.innerHTML=`<div class="eyebrow">Some, not unlimited</div><h2>Why doesn't a ₹1 price increase lose every customer?</h2><div class="visualCompare"><div class="visualPanel"><b>Perfect competition</b><p>Identical product. Buyer can switch instantly.</p><strong>Almost no individual price power</strong></div><div class="visualPanel"><b>Monopolistic competition</b><p>Differentiated brand. Some buyers prefer it.</p><strong>Some price power</strong></div></div>`;
else if(t==='graph')m.innerHTML=`<div class="eyebrow">Graph it</div><h2>The firm's demand/AR curve slopes downward.</h2><div class="graphExplain"><svg viewBox="0 0 620 330" role="img" aria-label="Downward sloping demand curve"><line x1="70" y1="280" x2="585" y2="280" class="chartAxis"/><line x1="70" y1="280" x2="70" y2="35" class="chartAxis"/><g class="chartGrid"><line x1="70" y1="220" x2="585" y2="220"/><line x1="70" y1="160" x2="585" y2="160"/><line x1="70" y1="100" x2="585" y2="100"/></g><path d="M110 80 C240 120 390 190 550 255" class="marketCurve downLine"/><text x="470" y="235" class="chartLabel">AR / Demand</text><text x="15" y="55" class="chartLabel">Price</text><text x="505" y="315" class="chartLabel">Quantity</text></svg><div class="notice"><b>Read it:</b> to sell more, the firm generally has to accept a lower price. So its demand/AR curve slopes downward.</div></div><div class="notice"><b>But note:</b> close substitutes from other brands usually make demand more elastic than under a strong monopoly.</div>`;
else if(t==='comparePc')m.innerHTML=`<div class="eyebrow">Exam comparison</div><h2>Perfect vs monopolistic competition</h2><div class="tableWrap"><table class="table"><thead><tr><th>Basis</th><th>Perfect competition</th><th>Monopolistic competition</th></tr></thead><tbody><tr><td>Product</td><td>Homogeneous</td><td>Differentiated</td></tr><tr><td>Price influence</td><td>Price taker</td><td>Some control over own product price</td></tr><tr><td>AR and MR</td><td>AR = MR</td><td>AR &gt; MR</td></tr><tr><td>Firm demand curve</td><td>Perfectly elastic / horizontal</td><td>Downward sloping</td></tr></tbody></table></div><div class="notice">This exact comparison pattern appears in CISCE examiner material.</div>`;
else if(t==='transfer')m.innerHTML=`<div class="eyebrow">ISC transfer</div><h2>Identify the structure.</h2><div class="caseFile"><p>A city has many movie theatres. They offer the same broad service but differ by location, seating, screens, ambience and loyalty programmes. Each theatre has limited influence over its own ticket price.</p></div><div class="answers"><button class="ans q" data-v="mc">Monopolistic competition</button><button class="ans q" data-v="pc">Perfect competition</button><button class="ans q" data-v="mo">Monopoly</button></div><div id="fb" class="feedback"></div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board answer</div><h2>Differentiate perfect and monopolistic competition.</h2><div class="board"><p><b>Nature of product:</b> firms under perfect competition sell a homogeneous product, whereas firms under monopolistic competition sell differentiated products.</p><p><b>Price influence:</b> a perfectly competitive firm is a price taker, whereas a monopolistically competitive firm has some control over the price of its own differentiated product.</p><p><b>Demand curve:</b> the individual firm's demand curve is horizontal under perfect competition and downward sloping under monopolistic competition.</p></div><div class="callout">Use a <b>common basis of contrast</b> in both columns/sentences.</div>`;
else if(t==='boss')m.innerHTML=`<div class="eyebrow">Boss battle</div><h2>Many firms + differentiated products + relatively free entry. Strongest answer?</h2><div class="answers"><button class="ans q" data-v="mc">Monopolistic competition</button><button class="ans q" data-v="ol">Oligopoly</button><button class="ans q" data-v="pc">Perfect competition</button></div><div id="fb" class="feedback"></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>Product differentiation unlocked.</h1><a class="btn primary" href="mission.html?mission=market-5">Next: Oligopoly & Monopsony →</a>`;
if(t==='racketScene')quiz('diff','Exactly. Buyers perceive differences, so brands are not perfect substitutes.');if(t==='hook')quiz('different','Exactly. Perceived differences create room for brand preference and some price control.');if(t==='differentiate')quiz('brand','Correct. Same broad service, but meaningful differences between sellers.');if(t==='transfer')quiz('mc','Correct. Many sellers + differentiated experience + some price control = monopolistic competition.');if(t==='boss')quiz('mc','Correct. Product differentiation separates it from perfect competition.');finish()}
render();
