const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'market-1'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook", "market", "whoIsWho", "roleSwitch", "essentials", "structure", "situationLens", "factors", "classify", "tree", "surroundings", "formal", "transfer", "board", "finish"]; const labels={"hook": "Start with your world", "market": "What is a market?", "essentials": "Essentials of a market", "structure": "Market structure", "factors": "What determines the form?", "classify": "The four seller-side forms", "tree": "Classification tree", "surroundings": "Examples around you", "formal": "ISC layer", "transfer": "Transfer practice", "board": "Board answer", "finish": "Mission complete", "whoIsWho": "Who is buying from whom?", "roleSwitch": "Buyer or seller depends on the deal", "situationLens": "Read the situation first"}; const help={"hook": "We are not naming market forms yet. First notice that some sellers have almost no power while others have a lot. Market structure is the reason.", "market": "A market is any arrangement through which buyers and sellers can communicate and exchange. They do not need to meet physically.", "essentials": "For a market to make economic sense, think buyer, seller, something being exchanged, and a way for them to interact over price/quantity.", "structure": "Market structure means the competitive environment a firm operates in. It is not a building.", "factors": "These factors are clues. Number of firms alone is not always enough. Product similarity, entry barriers, knowledge, selling costs and price influence help distinguish the forms.", "classify": "Perfect competition and monopolistic competition both have many sellers. The product is the big separator: homogeneous versus differentiated.", "tree": "A decision tree is a reasoning aid. It does not mean every real industry fits perfectly, but it matches the textbook models.", "surroundings": "Use the surroundings only as intuition. Real markets may not be textbook-perfect. In an exam, classify from the facts given in the question.", "formal": "This screen converts the intuition into the vocabulary you need to write in ISC answers.", "transfer": "A transfer question changes the story. Ignore the unfamiliar product and hunt for the same clues.", "board": "A good board answer defines the term first, then explains the factors in complete sentences.", "finish": "You now have the diagnostic framework needed for the next five missions.", "whoIsWho": "A buyer is the person or organisation acquiring a good or service. A seller is the person or organisation offering it. Ask: who gives the good or service, and who pays for it?", "roleSwitch": "Buyer and seller are roles in a particular transaction, not permanent identities. The same person can buy one thing and sell another.", "situationLens": "Before classifying a market, write down the buyers, the sellers, what is being exchanged, and the conditions surrounding that exchange."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look again at the economic clue, not the brand name or story.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function finish(){save();header()}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 1</div><h1>Same shopping trip. Very different seller power.</h1><div class="worldGrid"><div class="worldCard"><div class="emojiHero">🥬🥬🥬</div><b>Vegetable stalls</b><p>Lots of nearby sellers. Charging wildly more is difficult.</p></div><div class="worldCard"><div class="emojiHero">🎮</div><b>Game consoles</b><p>Only a few major ecosystems. Each watches the others.</p></div><div class="worldCard"><div class="emojiHero">⚡</div><b>Local utility</b><p>Sometimes one provider dominates a service area.</p></div></div><div class="callout"><b>Our chapter question:</b> What features of a market decide how much power a firm has?</div>`;
else if(t==='market')m.innerHTML=`<div class="eyebrow">9.1 Concept of Market</div><h2>A market does not need stalls, cash, or even a physical place.</h2><div class="visualCompare"><div class="visualPanel"><div class="emojiHero">🎟️</div><h3>Movie ticket app</h3><p>You choose a cinema, showtime and price online.</p></div><div class="equalsBig">=</div><div class="visualPanel"><div class="emojiHero">🥕</div><h3>Vegetable bazaar</h3><p>You compare sellers face to face.</p></div></div><div class="definition"><div class="term">ISC-ready meaning</div><p>A <b>market</b> is an arrangement through which buyers and sellers come into contact for the purchase and sale of goods or services.</p></div><div class="questionCard"><b>Which is NOT necessary for a market?</b><div class="answers"><button class="ans q" data-v="physical">A physical building</button><button class="ans q" data-v="buyers">Buyers</button><button class="ans q" data-v="sellers">Sellers</button><button class="ans q" data-v="exchange">Interaction for exchange</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='whoIsWho')m.innerHTML=`<div class="eyebrow">Build the intuition</div><h2>Who is buying from whom?</h2><div class="scenarioBoard"><div class="roleCard buyer"><div class="emojiHero">🧑</div><h3>You</h3><p>You want to watch a movie tonight.</p><span class="roleTag">BUYER</span></div><div class="tradeArrow"><span>₹ ticket price</span><b>→</b><span>← seat + screening service</span></div><div class="roleCard seller"><div class="emojiHero">🎬</div><h3>Movie theatre</h3><p>It offers seats and the cinema experience for sale.</p><span class="roleTag">SELLER</span></div></div><div class="conceptStrip"><div><b>Buyer</b><span>demands or purchases</span></div><div><b>Seller</b><span>supplies or offers for sale</span></div><div><b>Exchange</b><span>a good or a service</span></div></div><div class="notice"><b>Buyer and seller are simply the two sides of an exchange.</b></div>`;
else if(t==='roleSwitch')m.innerHTML=`<div class="eyebrow">Roles change with the transaction</div><h2>The same person can be a buyer now and a seller five minutes later.</h2><div class="twoScene"><div class="scenePanel"><h3>Scene A: tennis lesson</h3><div class="miniFlow"><span>🧑 You</span><b>₹ →</b><span>🎾 Coach</span></div><p>You are the <b>buyer</b> of coaching. The coach is the <b>seller</b>.</p></div><div class="scenePanel"><h3>Scene B: coach buys a racket</h3><div class="miniFlow"><span>🎾 Coach</span><b>₹ →</b><span>🏪 Sports shop</span></div><p>Now the coach is the <b>buyer</b>. The sports shop is the <b>seller</b>.</p></div></div><div class="callout"><b>Ask “buyer of what?” and “seller of what?”</b> The role belongs to the transaction.</div>`;
else if(t==='essentials')m.innerHTML=`<div class="eyebrow">Build the idea</div><h2>What has to exist before we can talk about a market?</h2><div class="diagramRow"><div class="diagramPill">🙋 Buyer</div><div class="diagramArrow">↔</div><div class="diagramPill">🏪 Seller</div><div class="diagramArrow">↔</div><div class="diagramPill">📦 Good / service</div><div class="diagramArrow">↔</div><div class="diagramPill">💬 Contact & exchange</div></div><div class="notice"><b>Notice:</b> the “contact” can be face-to-face, a website, an app, a broker, a phone call, or another communication system.</div>`;
else if(t==='structure')m.innerHTML=`<div class="eyebrow">9.2 Market Structure</div><h2>Market structure tells us what competition looks like.</h2><div class="causeChain"><div><b>Market conditions</b><span>How many firms? What kind of product? Can rivals enter?</span></div><div class="chainArrow">→</div><div><b>Firm power</b><span>How much influence does one firm have over price?</span></div><div class="chainArrow">→</div><div><b>Firm behaviour</b><span>Price taking, branding, strategic reactions, etc.</span></div></div><div class="definition"><div class="term">ISC-ready meaning</div><p><b>Market structure</b> refers to the competitive characteristics or organisational features of a market which influence the behaviour of firms.</p></div>`;
else if(t==='situationLens')m.innerHTML=`<div class="eyebrow">Read the market situation</div><h2>Before naming the market form, freeze the scene.</h2><div class="caseFile"><h3>🎮 Console market</h3><p>Gamers choose among a few major console ecosystems. The companies watch one another's prices, exclusives and subscription moves.</p></div><div class="fourLens"><div><b>🙋 Buyers</b><span>Gamers</span></div><div><b>🏢 Sellers</b><span>Major console companies</span></div><div><b>📦 Exchange</b><span>Consoles, games, subscriptions</span></div><div><b>🌍 Situation</b><span>Few major sellers; rival decisions matter</span></div></div><div class="notice">Describe the scene first. Attach the economics label second.</div>`;
else if(t==='factors')m.innerHTML=`<div class="eyebrow">9.2.1 Factors determining market forms</div><h2>Use these as your Market Detective clues.</h2><div class="factorGrid"><div><b>👥 Number of buyers & sellers</b><span>One? Few? Many?</span></div><div><b>📦 Nature of product</b><span>Homogeneous or differentiated?</span></div><div><b>🚪 Entry and exit</b><span>Free or restricted by barriers?</span></div><div><b>💸 Price influence</b><span>Price taker or price maker?</span></div><div><b>📣 Selling costs</b><span>Does branding/advertising matter?</span></div><div><b>🧠 Knowledge & mobility</b><span>How freely can information and resources move?</span></div></div><div class="callout"><b>Do not memorize the list as six unrelated bullets.</b> They all answer one thing: how competitive is this market?</div>`;
else if(t==='classify')m.innerHTML=`<div class="eyebrow">9.2.2 Classification</div><h2>The four seller-side market forms</h2><div class="marketSpectrum v2"><div><b>VERY MANY</b><span>Perfect competition</span><small>homogeneous product</small></div><div><b>MANY</b><span>Monopolistic competition</span><small>differentiated product</small></div><div><b>FEW</b><span>Oligopoly</span><small>firms watch rivals</small></div><div><b>ONE</b><span>Monopoly</span><small>single seller</small></div></div><div class="notice"><b>Monopsony</b> sits outside this seller spectrum because it classifies the <em>buyer</em> side: one buyer.</div>`;
else if(t==='tree')m.innerHTML=`<div class="eyebrow">Diagram</div><h2>Classify by evidence, not by vibes.</h2><div class="flowTree"><div class="flowRoot">How many important sellers?</div><div class="flowBranches"><div><b>ONE</b><span>Monopoly</span></div><div><b>FEW</b><span>Oligopoly</span></div><div><b>MANY</b><span>Ask about the product ↓</span></div></div><div class="flowRoot secondaryFlow">If many sellers: are products homogeneous?</div><div class="flowBranches two"><div><b>YES</b><span>Perfect competition</span></div><div><b>NO</b><span>Monopolistic competition</span></div></div></div>`;
else if(t==='surroundings')m.innerHTML=`<div class="eyebrow">Your surroundings</div><h2>What clues would you inspect?</h2><div class="worldGrid"><div class="worldCard"><div class="emojiHero">🎾</div><b>Tennis rackets</b><p>Different brands, designs and reputations. Ask how many major firms and how differentiated they are.</p></div><div class="worldCard"><div class="emojiHero">🍿</div><b>Movie theatres</b><p>Same broad service, but location, screens, seats and experience can differentiate sellers.</p></div><div class="worldCard"><div class="emojiHero">🎮</div><b>Console ecosystems</b><p>A few large rivals make strategic moves and react to each other.</p></div></div><div class="callout">Real industries can be messy. <b>Exam rule:</b> classify from the features stated in the question.</div>`;
else if(t==='formal')m.innerHTML=`<div class="eyebrow">ISC vocabulary</div><h2>Translate intuition into exam language.</h2><div class="tableWrap"><table class="table marketTable"><thead><tr><th>Form</th><th>Core meaning</th><th>Signature clue</th></tr></thead><tbody><tr><td>Perfect competition</td><td>Very many firms selling a homogeneous product</td><td>Individual firm is a price taker</td></tr><tr><td>Monopolistic competition</td><td>Many firms selling differentiated products</td><td>Product differentiation</td></tr><tr><td>Oligopoly</td><td>Few large firms</td><td>Mutual interdependence</td></tr><tr><td>Monopoly</td><td>Single seller with no close substitute</td><td>Strong barriers to entry</td></tr><tr><td>Monopsony</td><td>Single buyer</td><td>Buyer-side market power</td></tr></tbody></table></div>`;
else if(t==='transfer')m.innerHTML=`<div class="eyebrow">ISC-style transfer</div><h2>Forget the product. Read the clues.</h2><div class="caseFile"><b>CASE</b><p>A market has a large number of sellers. Each seller offers a slightly different version of the product and can influence the price of its own brand to some extent.</p></div><div class="answers"><button class="ans q" data-v="mc">Monopolistic competition</button><button class="ans q" data-v="pc">Perfect competition</button><button class="ans q" data-v="ol">Oligopoly</button><button class="ans q" data-v="mo">Monopoly</button></div><div id="fb" class="feedback"></div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board answer</div><h2>Explain any three factors that determine market structure.</h2><div class="board"><p><b>Model structure:</b></p><p>1. <b>Number of buyers and sellers:</b> the greater the number of independent sellers, the less influence one seller normally has over market price.</p><p>2. <b>Nature of product:</b> products may be homogeneous or differentiated, affecting the degree of competition and price control.</p><p>3. <b>Freedom of entry and exit:</b> strong barriers protect existing firms, while free entry increases competitive pressure.</p></div><div class="questionCard"><b>Which answer style is strongest for ISC?</b><div class="answers"><button class="ans q" data-v="explain">Name a factor and explain how it changes competition.</button><button class="ans q" data-v="list">Write only: sellers, product, entry.</button></div><div id="fb" class="feedback"></div></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>You can now read a market.</h1><p class="big">Next: perfect competition, where we explain exactly why one firm cannot set its own price.</p><a class="btn primary" href="mission.html?mission=market-2">Start Mission 2 →</a>`;
if(t==='market')quiz('physical','Correct. A physical place is optional; interaction between buyers and sellers is what matters.');if(t==='transfer')quiz('mc','Correct. Many firms + differentiated products + some price influence is monopolistic competition.');if(t==='board')quiz('explain','Exactly. ISC answers need the economic implication, not a bare list.','A bare list may earn less because the question asks you to explain.');finish()}
render();
