const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'market-2'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook", "meaning", "features", "homogeneous", "entry", "purePerfect", "priceTaker", "firmIndustry", "graph", "arMr", "transfer", "board", "boss", "finish"]; const labels={"hook": "Tomato seller challenge", "meaning": "Meaning", "features": "Features", "homogeneous": "Homogeneous product", "entry": "Free entry & knowledge", "purePerfect": "Pure vs perfect competition", "priceTaker": "Why price taker?", "firmIndustry": "Firm vs industry", "graph": "Firm demand curve", "arMr": "AR = MR = Price", "transfer": "Transfer question", "board": "Board answer", "boss": "Boss battle", "finish": "Mission complete"}; const help={"hook": "Imagine you are one tiny seller among thousands. The market is much bigger than you.", "meaning": "Perfect competition is a theoretical benchmark. Real markets may only resemble it.", "features": "Each feature supports intense competition. Do not treat them as decorative bullets.", "homogeneous": "Homogeneous means buyers regard the units sold by different firms as identical for the purpose of purchase.", "entry": "Free entry means firms can enter when profit attracts them; perfect knowledge prevents a seller from exploiting ignorance.", "purePerfect": "Pure competition uses a smaller set of assumptions. Perfect competition adds further conditions such as perfect knowledge and factor mobility.", "priceTaker": "A price taker accepts the market-determined price because one tiny firm cannot shift the whole market price.", "firmIndustry": "A firm is one producing unit; an industry is the collection of firms producing the commodity.", "graph": "This horizontal line belongs to one perfectly competitive firm, not to the entire market demand curve.", "arMr": "Average revenue is price per unit. When price is constant for every unit, marginal revenue also equals that price.", "transfer": "Transfer means the product changes but the logic stays the same.", "board": "For a \u201cwhy\u201d answer, connect the feature to the result: many sellers + homogeneous product \u2192 no individual price control.", "boss": "The boss mixes firm/industry and graph concepts because CISCE examiners report confusion here.", "finish": "You have the base needed for producer equilibrium under perfect competition later."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look again at the economic clue, not the brand name or story.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function finish(){save();header()}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 2</div><h1>You are Tomato Seller #8,431.</h1><div class="scene"><p class="big">Everyone nearby sells tomatoes buyers consider essentially identical. Market price: <b>₹40/kg</b>.</p></div><div class="questionCard"><b>You put up a sign: ₹65/kg. What is most likely?</b><div class="answers"><button class="ans q" data-v="leave">Buyers switch to other sellers.</button><button class="ans q" data-v="follow">Everyone happily follows your price.</button><button class="ans q" data-v="market">Your stall changes the national market price.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='meaning')m.innerHTML=`<div class="eyebrow">9.3 Perfect Competition</div><h2>Maximum competitive pressure on an individual firm.</h2><div class="definition"><div class="term">ISC-ready definition</div><p><b>Perfect competition</b> is a market form with a very large number of buyers and sellers, a homogeneous product, free entry and exit, and conditions under which an individual firm has no control over market price.</p></div><div class="notice">The individual firm is therefore a <b>price taker</b>.</div>`;
else if(t==='features')m.innerHTML=`<div class="eyebrow">Features</div><h2>Every feature helps explain the firm's tiny power.</h2><div class="factorGrid"><div><b>👥 Very many buyers & sellers</b><span>One firm is tiny relative to market.</span></div><div><b>📦 Homogeneous product</b><span>Buyers see rival units as identical.</span></div><div><b>🚪 Free entry & exit</b><span>Profit attracts new firms; losses push firms out.</span></div><div><b>🧠 Perfect knowledge</b><span>Prices and conditions are known.</span></div><div><b>🚚 Factor mobility</b><span>Resources can move between uses.</span></div><div><b>📣 No need for product selling costs</b><span>Identical product reduces brand-based competition.</span></div></div>`;
else if(t==='homogeneous')m.innerHTML=`<div class="eyebrow">Homogeneous product</div><h2>If buyers see no meaningful difference, your brand cannot rescue a higher price.</h2><div class="visualCompare"><div class="visualPanel"><div class="emojiHero">🍅</div><b>Seller A tomato</b><p>₹40</p></div><div class="equalsBig">≈</div><div class="visualPanel"><div class="emojiHero">🍅</div><b>Seller B tomato</b><p>₹40</p></div></div><div class="questionCard"><b>If A charges ₹60 for an identical product readily available at ₹40:</b><div class="answers"><button class="ans q" data-v="switch">buyers can switch to B.</button><button class="ans q" data-v="loyal">buyers must remain loyal to A.</button></div><div id="fb" class="feedback"></div></div>`;
else if(t==='entry')m.innerHTML=`<div class="eyebrow">Why entry matters</div><h2>High profits act like an invitation.</h2><div class="causeChain"><div><b>Existing firms earn unusually high profits</b></div><div class="chainArrow">→</div><div><b>New firms can enter</b></div><div class="chainArrow">→</div><div><b>Competitive pressure rises</b></div></div><div class="callout"><b>Perfect knowledge</b> strengthens this: buyers and sellers are assumed to know relevant market conditions.</div>`;
else if(t==='purePerfect')m.innerHTML=`<div class="eyebrow">9.3.3 Pure vs Perfect Competition</div><h2>Perfect competition asks for more conditions.</h2><div class="tableWrap"><table class="table"><thead><tr><th>Pure competition</th><th>Perfect competition</th></tr></thead><tbody><tr><td>Large number of buyers & sellers</td><td>Includes these conditions</td></tr><tr><td>Homogeneous product</td><td>+ perfect knowledge</td></tr><tr><td>Free entry & exit</td><td>+ perfect mobility of factors and other ideal conditions</td></tr></tbody></table></div><div class="notice"><b>Shortcut:</b> perfect competition is the stricter, more idealised model.</div>`;
else if(t==='priceTaker')m.innerHTML=`<div class="eyebrow">The central consequence</div><h2>Why is the firm a price taker?</h2><div class="causeChain"><div><b>Very many sellers</b><span>One firm supplies a tiny share.</span></div><div class="chainArrow">+</div><div><b>Homogeneous product</b><span>Buyer can switch easily.</span></div><div class="chainArrow">→</div><div><b>No individual price control</b><span>Firm accepts market price.</span></div></div><div class="definition"><div class="term">Price taker</div><p>A firm which accepts the price determined by market forces and cannot independently influence it.</p></div>`;
else if(t==='firmIndustry')m.innerHTML=`<div class="eyebrow">Exam trap</div><h2>Firm ≠ industry</h2><div class="visualCompare"><div class="visualPanel"><div class="emojiHero">🏪</div><h3>Firm</h3><p>One individual producer.</p></div><div class="notEqual">≠</div><div class="visualPanel"><div class="emojiHero">🏪🏪🏪</div><h3>Industry</h3><p>All firms producing the commodity.</p></div></div><div class="callout">CISCE's 2024 examiner report specifically recommended clarifying this distinction.</div>`;
else if(t==='graph')m.innerHTML=`<div class="eyebrow">Graph it</div><h2>The perfectly competitive firm's demand curve is horizontal.</h2><div class="graphExplain"><svg viewBox="0 0 620 330" role="img" aria-label="Horizontal demand curve of a perfectly competitive firm"><line x1="70" y1="280" x2="585" y2="280" class="chartAxis"/><line x1="70" y1="280" x2="70" y2="35" class="chartAxis"/><g class="chartGrid"><line x1="70" y1="220" x2="585" y2="220"/><line x1="70" y1="160" x2="585" y2="160"/><line x1="70" y1="100" x2="585" y2="100"/></g><line x1="85" y1="160" x2="565" y2="160" class="marketCurve pcLine"/><text x="500" y="145" class="chartLabel">AR = MR = Price</text><text x="15" y="55" class="chartLabel">Price</text><text x="505" y="315" class="chartLabel">Quantity</text><circle cx="175" cy="160" r="7" class="chartDot"/><circle cx="330" cy="160" r="7" class="chartDot"/><circle cx="485" cy="160" r="7" class="chartDot"/></svg><div class="notice"><b>Read it:</b> the firm can change quantity sold while the market price stays the same. That is why its demand/AR curve is horizontal.</div></div><div class="graphSteps"><div><b>1</b><span>Y-axis = Price / AR / MR</span></div><div><b>2</b><span>X-axis = Quantity sold by the firm</span></div><div><b>3</b><span>Same market price at different quantities</span></div><div><b>4</b><span>So the line is parallel to the X-axis</span></div></div>`;
else if(t==='arMr')m.innerHTML=`<div class="eyebrow">Revenue link</div><h2>Why AR = MR = Price</h2><div class="mathStory"><div><b>Price</b><strong>₹40</strong><span>for each unit</span></div><div><b>Average Revenue</b><strong>₹40</strong><span>TR ÷ Q</span></div><div><b>Marginal Revenue</b><strong>₹40</strong><span>extra revenue from one more unit</span></div></div><div class="equation">P = AR = MR</div>`;
else if(t==='transfer')m.innerHTML=`<div class="eyebrow">ISC-style transfer</div><h2>A seller cannot charge above the prevailing price.</h2><div class="caseFile"><p>A commodity is sold by a very large number of firms. Buyers regard every firm's product as identical and know the prevailing market price.</p></div><div class="answers"><button class="ans q" data-v="pc">Perfect competition</button><button class="ans q" data-v="mc">Monopolistic competition</button><button class="ans q" data-v="mo">Monopoly</button></div><div id="fb" class="feedback"></div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board answer</div><h2>Why is a perfectly competitive firm a price taker?</h2><div class="board"><p>Under perfect competition there are a very large number of sellers and the product is homogeneous. The output of an individual firm is only a very small part of total market supply. If it charges above the market price, buyers can purchase the identical product from other sellers. Therefore the firm cannot influence market price and must accept the price determined by the industry.</p></div><div class="callout"><b>Board habit:</b> do not merely write “many sellers.” Explain why that removes price power.</div>`;
else if(t==='boss')m.innerHTML=`<div class="eyebrow">Boss battle</div><h2>Which curve belongs to ONE perfectly competitive firm?</h2><div class="answers"><button class="ans q" data-v="horizontal">A horizontal demand/AR curve at the market price</button><button class="ans q" data-v="down">A downward-sloping market demand curve</button><button class="ans q" data-v="vertical">A vertical demand curve</button></div><div id="fb" class="feedback"></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>Price taker unlocked.</h1><p class="big">Next: monopoly. What changes when there is only one seller?</p><a class="btn primary" href="mission.html?mission=market-3">Start Monopoly →</a>`;
if(t==='hook')quiz('leave','Exactly. With many sellers of an identical product, buyers can switch.');if(t==='homogeneous')quiz('switch','Correct. Homogeneity makes switching easy.');if(t==='transfer')quiz('pc','Correct. Very many firms + homogeneous product + no individual price power points to perfect competition.');if(t==='boss')quiz('horizontal','Correct. The individual firm faces a perfectly elastic demand/AR curve at the given market price.');finish()}
render();