const $=id=>document.getElementById(id);
const META=window.MISSION_META[new URLSearchParams(location.search).get('mission')||'market-3'];
const KEY=META.storageKey;
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=["hook", "meaning", "features", "barriers", "power", "notUnlimited", "graph", "priceDiscrimination", "monoVsMonopsony", "transfer", "board", "boss", "finish"]; const labels={"hook": "Only seller", "meaning": "Meaning", "features": "Features", "barriers": "Barriers to entry", "power": "Price maker", "notUnlimited": "Power has limits", "graph": "Demand curve", "priceDiscrimination": "Price discrimination case", "monoVsMonopsony": "Monopoly vs monopsony", "transfer": "ISC transfer", "board": "Board answer", "boss": "Boss battle", "finish": "Mission complete"}; const help={"hook": "One seller changes the competitive situation dramatically because buyers cannot simply move to an identical rival.", "meaning": "Monopoly means one seller, not one buyer. The product has no close substitute in the model.", "features": "The features reinforce one another: barriers protect the single seller, while lack of close substitutes limits buyer alternatives.", "barriers": "Barriers are obstacles that make entry difficult, such as legal protection, control of essential resources, high setup costs or technology.", "power": "A monopolist has price influence, but its price and quantity choices are still constrained by demand.", "notUnlimited": "If price rises, quantity demanded can fall. \u201cPrice maker\u201d never means customers become irrelevant.", "graph": "This is the market demand curve because the monopolist is the market\u2019s sole seller.", "priceDiscrimination": "Charging different prices for the same product/service to different buyers or markets can be called price discrimination when conditions permit.", "monoVsMonopsony": "Monopoly = one seller. Monopsony = one buyer. Ask which side has the \u201cone.\u201d", "transfer": "Read the scenario and identify the structural clue first.", "board": "Definitions plus reasons score better than slogans.", "boss": "The exam may disguise monopoly inside a story about a sole producer.", "finish": "Next we move to many sellers again, but with differentiated products."};
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(k='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[k]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(txt,ok=true){const e=$('fb');if(!e)return;e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(correct,why,wrong='Look again at the economic clue, not the brand name or story.'){document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{document.querySelectorAll('.q').forEach(x=>x.classList.remove('selected','correct','wrong'));b.classList.add('selected');if(b.dataset.v===correct){b.classList.add('correct');fb('✓ '+why,true);reward()}else{b.classList.add('wrong');fb(wrong,false);miss()}})}
function finish(){save();header()}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{document.querySelector('.helpBox')?.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
function render(){header();const t=screens[state.i],m=$('main');
if(t==='hook')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 3</div><h1>There is no shop next door.</h1><div class="visualCompare"><div class="visualPanel"><div class="emojiHero">🏪</div><h3>One seller</h3><p>Customers cannot switch to another seller of the same product.</p></div><div class="equalsBig">→</div><div class="visualPanel"><div class="emojiHero">💸</div><h3>More price influence</h3><p>But demand still limits what the seller can do.</p></div></div>`;
else if(t==='meaning')m.innerHTML=`<div class="eyebrow">9.4 Monopoly</div><h2>One seller. No close substitute.</h2><div class="definition"><div class="term">ISC-ready definition</div><p><b>Monopoly</b> is a market form in which there is a single seller of a commodity for which there are no close substitutes and entry of new firms is restricted.</p></div>`;
else if(t==='features')m.innerHTML=`<div class="eyebrow">Features</div><h2>Build the monopoly from its conditions.</h2><div class="factorGrid"><div><b>1️⃣ Single seller</b><span>The firm and industry coincide on the seller side.</span></div><div><b>🚫 No close substitutes</b><span>Buyers lack a very similar alternative.</span></div><div><b>🧱 Barriers to entry</b><span>Potential rivals cannot enter freely.</span></div><div><b>💸 Price influence</b><span>The firm has substantial control over price.</span></div><div><b>📉 Downward demand</b><span>Higher price generally means lower quantity demanded.</span></div></div>`;
else if(t==='barriers')m.innerHTML=`<div class="eyebrow">Why doesn't competition appear?</div><h2>Because entry can be blocked.</h2><div class="barrierWall"><div>📜 Legal / patent protection</div><div>🏭 Very high setup cost</div><div>⛏️ Control over an essential resource</div><div>🧠 Technology / network advantages</div></div><div class="notice"><b>Logic:</b> if rivals could freely enter and sell a close substitute, the seller would not remain a protected monopoly.</div>`;
else if(t==='power')m.innerHTML=`<div class="eyebrow">Price maker</div><h2>The monopolist chooses within a demand constraint.</h2><div class="causeChain"><div><b>One seller</b></div><div class="chainArrow">+</div><div><b>No close substitute</b></div><div class="chainArrow">→</div><div><b>Substantial price control</b></div></div><div class="definition"><div class="term">Price maker</div><p>A firm with sufficient market power to influence the price of its product, rather than simply accepting a market-given price.</p></div>`;
else if(t==='notUnlimited')m.innerHTML=`<div class="eyebrow">Misconception repair</div><h2>“Monopoly can charge literally anything.”</h2><div class="answers"><button class="ans q" data-v="false">False. Quantity demanded still responds to price.</button><button class="ans q" data-v="true">True. A monopolist can force every buyer to pay any price.</button></div><div id="fb" class="feedback"></div><div class="callout">Seller power is <b>greater</b>, not infinite.</div>`;
else if(t==='graph')m.innerHTML=`<div class="eyebrow">Graph it</div><h2>The monopolist faces a downward-sloping demand / AR curve.</h2><div class="graphExplain"><svg viewBox="0 0 620 330" role="img" aria-label="Downward sloping demand curve"><line x1="70" y1="280" x2="585" y2="280" class="chartAxis"/><line x1="70" y1="280" x2="70" y2="35" class="chartAxis"/><g class="chartGrid"><line x1="70" y1="220" x2="585" y2="220"/><line x1="70" y1="160" x2="585" y2="160"/><line x1="70" y1="100" x2="585" y2="100"/></g><path d="M110 80 C240 120 390 190 550 255" class="marketCurve downLine"/><text x="470" y="235" class="chartLabel">AR / Demand</text><text x="15" y="55" class="chartLabel">Price</text><text x="505" y="315" class="chartLabel">Quantity</text></svg><div class="notice"><b>Read it:</b> to sell more, the firm generally has to accept a lower price. So its demand/AR curve slopes downward.</div></div><div class="graphSteps"><div><b>1</b><span>Y-axis = Price / AR</span></div><div><b>2</b><span>X-axis = Quantity</span></div><div><b>3</b><span>To sell more, price generally must fall</span></div><div><b>4</b><span>Unlike perfect competition, the firm is not facing a fixed market price</span></div></div>`;
else if(t==='priceDiscrimination')m.innerHTML=`<div class="eyebrow">Exam-inspired case</div><h2>Same seller. Different markets. Different prices.</h2><div class="caseFile"><b>INSPIRED BY AN ISC SPECIMEN PATTERN</b><p>A sole producer sells the same product at a higher price in one city and a lower price in another.</p></div><div class="questionCard"><b>What market structure is immediately indicated by “sole producer”?</b><div class="answers"><button class="ans q" data-v="mo">Monopoly</button><button class="ans q" data-v="ol">Oligopoly</button><button class="ans q" data-v="mp">Monopsony</button></div><div id="fb" class="feedback"></div></div><div class="notice">A CISCE specimen paper used this kind of scenario with a sole AC producer selling at different prices in Delhi and Mussoorie.</div>`;
else if(t==='monoVsMonopsony')m.innerHTML=`<div class="eyebrow">Do not mix these</div><h2>Which side has one?</h2><div class="visualCompare"><div class="visualPanel"><div class="emojiHero">1️⃣🏪</div><h3>Monopoly</h3><p>ONE <b>SELLER</b> → many buyers</p></div><div class="notEqual">≠</div><div class="visualPanel"><div class="emojiHero">👥➡️1️⃣</div><h3>Monopsony</h3><p>Many sellers → ONE <b>BUYER</b></p></div></div>`;
else if(t==='transfer')m.innerHTML=`<div class="eyebrow">ISC transfer</div><h2>Identify the market and explain one clue.</h2><div class="caseFile"><p>A company is the only supplier of a service in a region. New firms face very high infrastructure costs and consumers have no close substitute.</p></div><div class="answers"><button class="ans q" data-v="mo">Monopoly because there is one protected seller.</button><button class="ans q" data-v="pc">Perfect competition because many buyers exist.</button><button class="ans q" data-v="mp">Monopsony because there is one buyer.</button></div><div id="fb" class="feedback"></div>`;
else if(t==='board')m.innerHTML=`<div class="eyebrow">Board answer</div><h2>State and explain three features of monopoly.</h2><div class="board"><p><b>Single seller:</b> one firm supplies the commodity, so the firm represents the seller side of the industry.</p><p><b>No close substitutes:</b> consumers do not have a closely similar alternative to switch to.</p><p><b>Barriers to entry:</b> legal, technical, resource or cost barriers prevent rival firms from entering freely.</p></div>`;
else if(t==='boss')m.innerHTML=`<div class="eyebrow">Boss battle</div><h2>Why is the monopoly demand curve downward sloping?</h2><div class="answers"><button class="ans q" data-v="demand">Because even a sole seller must lower price to sell a larger quantity along the market demand curve.</button><button class="ans q" data-v="fixed">Because the market gives the monopolist one fixed price.</button><button class="ans q" data-v="buyers">Because there is only one buyer.</button></div><div id="fb" class="feedback"></div>`;
else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>Single-seller logic unlocked.</h1><a class="btn primary" href="mission.html?mission=market-4">Next: Brands & Product Differentiation →</a>`;
if(t==='notUnlimited')quiz('false','Correct. Monopoly has price power, but quantity demanded still responds.');if(t==='priceDiscrimination')quiz('mo','Correct. “Sole producer and seller” signals monopoly.');if(t==='transfer')quiz('mo','Correct. One seller + no close substitute + entry barriers = monopoly.');if(t==='boss')quiz('demand','Exactly. The monopolist faces market demand, so selling more generally requires a lower price.');finish()}
render();