const $=id=>document.getElementById(id);
const KEY='econ_market_m1_v1';
const DEFAULT={i:0,xp:0,streak:0,sound:true,rewarded:{}};
let state=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));
const screens=['intro','market','structure','detective','spectrum','scenarioFood','scenarioAir','monoBuyer','decisionTree','practice','formal','board','boss','finish'];
state.i=Math.max(0,Math.min(+state.i||0,screens.length-1));
const labels={intro:'Who has the power?',market:'What is a market?',structure:'What is market structure?',detective:'Market Detective toolkit',spectrum:'Seller spectrum',scenarioFood:'Street-food case',scenarioAir:'Airline case',monoBuyer:'Monopoly vs monopsony',decisionTree:'Classification map',practice:'Market Detective practice',formal:'ISC-ready summary',board:'Board answer coach',boss:'Boss battle',finish:'Mission complete'};
const help={
 intro:'Do not memorize the market names yet. First learn to look for clues: how many sellers, whether products are the same, how easy entry is, how much price power a firm has, and whether rivals react to each other.',
 market:'A market is not just a physical bazaar. It is any arrangement where buyers and sellers interact to exchange a good or service. An app store, airline route, vegetable bazaar and online game store can all be markets.',
 structure:'Market structure means the pattern of competition in a market. Think: who sells, what they sell, how easy it is to enter, and how much control sellers have.',
 detective:'Use the same five clues every time. This keeps you from memorizing five unrelated definitions.',
 spectrum:'The names become easier when you place them by seller count. Many sellers are on one end; one seller is on the other. Monopsony is different because it means one buyer.',
 scenarioFood:'Many food sellers can still sell different recipes and brands. Many sellers does not automatically mean perfect competition.',
 scenarioAir:'With only a few large firms, each one watches the others. That mutual reaction is the heart of oligopoly.',
 monoBuyer:'Mono means one, but ask one what? Monopoly = one seller. Monopsony = one buyer.',
 decisionTree:'This is a diagnostic map, not a perfect legal rule. Start with seller count, then ask whether products are identical or differentiated.',
 practice:'Say your reasoning out loud: “few sellers + rivals react = oligopoly,” not just the label.',
 formal:'For ISC, the syllabus requires features of perfect competition, monopolistic competition, oligopoly, monopoly, and the meaning of monopsony. This mission is the foundation before we teach each form in depth.',
 board:'A strong answer defines market structure and then uses relevant features such as number of sellers, nature of product, entry barriers and price control.',
 boss:'Use the clues. Ignore distracting details like whether the product is expensive or glamorous.',
 finish:'You should now be able to classify a market from clues instead of recalling a paragraph.'
};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function tone(kind='click'){if(!state.sound)return;try{const C=new(window.AudioContext||window.webkitAudioContext)(),o=C.createOscillator(),g=C.createGain(),m={good:[620,880,.1],bad:[220,170,.12],win:[523,1046,.22]}[kind]||[430,520,.05];o.connect(g);g.connect(C.destination);o.frequency.setValueAtTime(m[0],C.currentTime);o.frequency.exponentialRampToValueAtTime(m[1],C.currentTime+m[2]);g.gain.setValueAtTime(.03,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+m[2]);o.start();o.stop(C.currentTime+m[2])}catch(e){}}
function reward(n=20){if(!state.rewarded[state.i]){state.rewarded[state.i]=1;state.xp+=n}state.streak++;tone('good');save();header()}
function miss(){state.streak=0;tone('bad');save();header()}
function header(){$('xp').textContent=state.xp;$('streak').textContent=state.streak;$('snd').textContent=state.sound?'ON':'OFF';$('fill').style.width=((state.i+1)/screens.length*100)+'%';$('pageJump').innerHTML=screens.map((s,i)=>`<option value="${i}" ${i===state.i?'selected':''}>${i+1}. ${labels[s]}</option>`).join('')}
function fb(id,txt,ok=true){const e=$(id);e.className='feedback show '+(ok?'good':'bad');e.innerHTML=txt}
function quiz(sel,correct,why){document.querySelectorAll(sel).forEach(b=>b.onclick=()=>{document.querySelectorAll(sel).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(b.dataset.v===correct){fb('fb','✓ '+why,true);reward()}else{fb('fb','Not quite. '+why,false);miss()}})}
function render(){header();const t=screens[state.i],m=$('main');
 if(t==='intro')m.innerHTML=`<div class="eyebrow">Forms of Market • Mission 1</div><h1>Who has the power here?</h1><p class="big">Before we memorize words like <b>oligopoly</b>, learn to inspect a market like a detective.</p><div class="powerHero"><div><span>100 sellers</span><b>Low individual power</b></div><div class="powerArrow">→</div><div><span>1 seller</span><b>High individual power</b></div></div><div class="callout"><b>Your recurring question:</b> Who sells, what do they sell, and how much power does one firm have?</div>`;
 else if(t==='market')m.innerHTML=`<div class="eyebrow">Start with meaning</div><h2>A market is not necessarily a place.</h2><div class="photoLesson"><img src="https://upload.wikimedia.org/wikipedia/commons/c/c6/Street_food_in_Causeway_Bay.JPG" alt="Street food sellers"><div><h3>This is obviously a market.</h3><p>Buyers and sellers meet and exchange food.</p><p>But Amazon, a PlayStation store, or an airline booking website can also be markets.</p></div></div><div class="definition"><div class="term">Market</div><p>An arrangement through which buyers and sellers interact to exchange goods or services.</p><div class="formal"><b>Human version:</b> buyers + sellers + exchange. A physical bazaar is only one possible form.</div></div><div class="questionCard"><b>Which statement is correct?</b><div class="answers"><button class="ans q" data-v="a">A market must be a physical place.</button><button class="ans q" data-v="b">A market can exist online if buyers and sellers interact.</button></div><div id="fb" class="feedback"></div></div><p class="sourceNote">Photo: BrokenSphere / Wikimedia Commons, CC BY-SA 3.0.</p>`; 
 else if(t==='structure')m.innerHTML=`<div class="eyebrow">What are we classifying?</div><h2>Market structure = what competition looks like.</h2><div class="diagramStack"><div class="diagramNode">👥 Who is selling?</div><div class="diagramArrow">↓</div><div class="diagramNode">📦 Same product or different?</div><div class="diagramArrow">↓</div><div class="diagramNode">🚪 Can new firms enter?</div><div class="diagramArrow">↓</div><div class="diagramNode">💸 Can one firm influence price?</div><div class="diagramArrow">↓</div><div class="diagramNode">👀 Must firms react to rivals?</div></div><div class="callout">These clues create the market structure.</div>`;
 else if(t==='detective')m.innerHTML=`<div class="eyebrow">Your toolkit</div><h2>Use these 5 clues every single time.</h2><div class="detectiveGrid"><div class="detectiveCard"><b>1. Sellers</b><span>One, few, many?</span></div><div class="detectiveCard"><b>2. Product</b><span>Identical or differentiated?</span></div><div class="detectiveCard"><b>3. Entry</b><span>Easy or blocked?</span></div><div class="detectiveCard"><b>4. Price power</b><span>Can one firm set price?</span></div><div class="detectiveCard"><b>5. Rival reaction</b><span>Does one firm's move affect others?</span></div></div><div class="callout"><b>Market Detective:</b> Sellers → Product → Entry → Price power → Rival reaction.</div>`;
 else if(t==='spectrum')m.innerHTML=`<div class="eyebrow">See the big picture</div><h2>Start with the number of sellers.</h2><div class="marketSpectrum"><div><b>VERY MANY</b><span>Perfect competition</span></div><div><b>MANY</b><span>Monopolistic competition</span></div><div><b>FEW</b><span>Oligopoly</span></div><div><b>ONE</b><span>Monopoly</span></div></div><div class="callout"><b>Important:</b> seller count is only the first clue. Product differences, entry barriers and price power matter too.</div><div class="definition"><div class="term">Monopsony is the odd one out</div><p>It means <b>one buyer</b>, not one seller.</p></div>`;
 else if(t==='scenarioFood')m.innerHTML=`<div class="eyebrow">Case 1 • Food</div><h2>Twenty restaurants. Same market form as wheat farmers?</h2><div class="photoLesson"><img src="https://upload.wikimedia.org/wikipedia/commons/c/c6/Street_food_in_Causeway_Bay.JPG" alt="Food sellers"><div><ul class="bigList"><li>Many sellers</li><li>Different recipes and brands</li><li>Customers may prefer one seller</li><li>A seller can charge a little more without losing everyone</li></ul></div></div><div class="questionCard"><b>Which clue is doing the most work here?</b><div class="answers"><button class="ans q" data-v="same">The products are identical.</button><button class="ans q" data-v="diff">The products are differentiated.</button><button class="ans q" data-v="one">There is only one seller.</button></div><div id="fb" class="feedback"></div></div>`;
 else if(t==='scenarioAir')m.innerHTML=`<div class="eyebrow">Case 2 • Airlines</div><h2>What changes when only a few giant firms matter?</h2><div class="photoLesson"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Singapore_Airlines_aircraft_parked_at_Terminal_2_of_Singapore_Changi_Airport.jpg" alt="Commercial aircraft"><div><p class="big">Imagine only 3 major airlines serve a route.</p><p>Airline A cuts fares by 30%.</p><p><b>Can B and C safely ignore it?</b> Usually not. Their decisions are connected.</p></div></div><div class="definition"><div class="term">Interdependence</div><p>Each major firm must consider how rivals may react to its decisions.</p></div><div class="questionCard"><b>Few major sellers + strong rival reaction suggests…</b><div class="answers"><button class="ans q" data-v="oligo">Oligopoly</button><button class="ans q" data-v="perfect">Perfect competition</button><button class="ans q" data-v="mono">Monopsony</button></div><div id="fb" class="feedback"></div></div><p class="sourceNote">Photo: J. Petersen / Wikimedia Commons, CC BY 2.5.</p>`;
 else if(t==='monoBuyer')m.innerHTML=`<div class="eyebrow">One word trap</div><h2>Monopoly and monopsony are not the same.</h2><div class="compare cleanCompare"><div class="panel"><div class="bigIcon">🏪</div><h3>Monopoly</h3><p><b>ONE SELLER</b></p><p>Many buyers may face one seller.</p></div><div class="op">≠</div><div class="panel"><div class="bigIcon">🧑‍💼</div><h3>Monopsony</h3><p><b>ONE BUYER</b></p><p>Many sellers may face one dominant buyer.</p></div></div><div class="questionCard"><b>A mining town has many workers but only one company hiring miners. What is the key market feature?</b><div class="answers"><button class="ans q" data-v="buyer">One buyer of labour → monopsony</button><button class="ans q" data-v="seller">One seller of labour → monopoly</button></div><div id="fb" class="feedback"></div></div>`;
 else if(t==='decisionTree')m.innerHTML=`<div class="eyebrow">Classification map</div><h2>Use this instead of guessing.</h2><div class="flowTree"><div class="flowRoot">How many sellers?</div><div class="flowBranches"><div><b>ONE</b><span>→ Monopoly</span></div><div><b>FEW</b><span>→ Oligopoly</span></div><div><b>MANY</b><span>Ask another question ↓</span></div></div><div class="flowRoot secondaryFlow">Are products essentially identical?</div><div class="flowBranches two"><div><b>YES</b><span>→ Perfect competition</span></div><div><b>NO, differentiated</b><span>→ Monopolistic competition</span></div></div></div><div class="callout">Then confirm with entry barriers, price power and rival reaction. Real markets can be messy; this is the textbook classification logic.</div>`;
 else if(t==='practice')m.innerHTML=`<div class="eyebrow">Market Detective</div><h2>Classify from clues, not vibes.</h2><div class="caseFile"><b>CASE FILE</b><p>Hundreds of sellers. Each sells a branded, slightly different version of the product. Entry is fairly easy. Each seller has some price control.</p></div><div class="answers"><button class="ans q" data-v="mc">Monopolistic competition</button><button class="ans q" data-v="pc">Perfect competition</button><button class="ans q" data-v="ol">Oligopoly</button><button class="ans q" data-v="mo">Monopoly</button></div><div id="fb" class="feedback"></div>`;
 else if(t==='formal')m.innerHTML=`<div class="eyebrow">ISC layer</div><h2>Now attach the formal names to ideas you already understand.</h2><div class="tableWrap"><table class="table marketTable"><thead><tr><th>Form</th><th>Sellers</th><th>Product</th><th>Price power</th><th>Signature clue</th></tr></thead><tbody><tr><td>Perfect competition</td><td>Very many</td><td>Homogeneous</td><td>Virtually none</td><td>Price taker</td></tr><tr><td>Monopolistic competition</td><td>Many</td><td>Differentiated</td><td>Some</td><td>Brand/product differentiation</td></tr><tr><td>Oligopoly</td><td>Few</td><td>Either</td><td>Considerable</td><td>Interdependence</td></tr><tr><td>Monopoly</td><td>One</td><td>No close substitute</td><td>High</td><td>Strong entry barriers</td></tr><tr><td>Monopsony</td><td>Many sellers may exist</td><td>—</td><td>Buyer power</td><td>One buyer</td></tr></tbody></table></div><div class="callout">CISCE specifically names all five market forms in the Class XII syllabus. We will teach the detailed features of each in the next missions.</div>`;
 else if(t==='board')m.innerHTML=`<div class="eyebrow">Board answer coach</div><h2>What is market structure?</h2><div class="answerPreview"><h3>Build the answer</h3><div id="built"><p class="mini">Choose the best sentence.</p></div></div><div class="answers"><button class="ans q" data-v="good">Market structure refers to the competitive characteristics of a market, such as number of firms, nature of product, ease of entry and degree of price control.</button><button class="ans q" data-v="bad1">Market structure means the physical building where goods are sold.</button><button class="ans q" data-v="bad2">Market structure is determined only by the price of the product.</button></div><div id="fb" class="feedback"></div>`;
 else if(t==='boss')m.innerHTML=`<div class="eyebrow">Boss battle</div><h2>One buyer. Many sellers. Name it.</h2><div class="answers"><button class="ans q" data-v="monopsony">Monopsony</button><button class="ans q" data-v="monopoly">Monopoly</button><button class="ans q" data-v="oligopoly">Oligopoly</button></div><div id="fb" class="feedback"></div><div class="callout">Boss rule: identify whether the “one” refers to the buyer or seller.</div>`;
 else m.innerHTML=`<div class="eyebrow">Mission complete</div><h1>Market Detective unlocked 🔎</h1><p class="big">You can now classify markets from evidence instead of memorizing five definitions.</p><div class="detectiveGrid"><div class="detectiveCard"><b>Sellers</b><span>one / few / many</span></div><div class="detectiveCard"><b>Product</b><span>same / differentiated</span></div><div class="detectiveCard"><b>Entry</b><span>easy / difficult</span></div><div class="detectiveCard"><b>Price power</b><span>low / high</span></div><div class="detectiveCard"><b>Rivals</b><span>independent / interdependent</span></div></div><a class="btn primary" href="market.html">Back to Forms of Market map</a>`;
 if(t==='market')quiz('.q','b','Correct. The interaction matters, not whether buyers and sellers stand in the same place.');
 if(t==='scenarioFood')quiz('.q','diff','Exactly. Many sellers plus differentiated products points toward monopolistic competition.');
 if(t==='scenarioAir')quiz('.q','oligo','Exactly. Few major firms that react strategically to each other is oligopoly.');
 if(t==='monoBuyer')quiz('.q','buyer','Correct. The company is the sole buyer of labour, so this is monopsony.');
 if(t==='practice')quiz('.q','mc','Correct. Many sellers + differentiated products + some price control = monopolistic competition.');
 if(t==='board')document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{if(b.dataset.v==='good'){$('built').innerHTML='<div class="answerLine">Market structure refers to the competitive characteristics of a market, such as number of firms, nature of product, ease of entry and degree of price control.</div>';fb('fb','✓ Strong. It defines the idea and names the dimensions that create it.');reward(30)}else{fb('fb','That does not define market structure. Focus on the pattern of competition.',false);miss()}});
 if(t==='boss')quiz('.q','monopsony','Correct. Monopoly = one seller. Monopsony = one buyer.');
 save();
}
$('next').onclick=()=>{if(state.i<screens.length-1){state.i++;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('back').onclick=()=>{if(state.i>0){state.i--;save();render();scrollTo({top:0,behavior:'smooth'})}else location.href='market.html'};
$('hint').onclick=()=>{let old=document.querySelector('.helpBox');if(old)old.remove();$('main').insertAdjacentHTML('beforeend',`<div class="helpBox"><h3>I don't get it</h3><p>${help[screens[state.i]]}</p></div>`)};
$('sound').onclick=()=>{state.sound=!state.sound;save();header()};
$('pageJump').onchange=e=>{state.i=+e.target.value;save();render()};
render();
